# Join df's

Joining emr_cycle_event and emr_cycle_event to make type of responder dataset

What this notebook does, in order:
1. **Read in data from processing files** running scripts (emr_cycle_event_processing & emr_cycle_processing) to get cleaned datasets from those files
2. **Merge** cycle_id in response_df from emr_cycle_event_processing can be joined by id in df from emr_cycle_processing

## Setup

In [1]:
import pandas as pd
from processing import load_cycle_events, load_cycles, profile

In [4]:
#pip install nbformat

In [2]:
#setting display options to show all columns and full width
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)        # Allow full width

## 1. Run Processing Scripts

Run each processing script to build its cleaned dataframe

In [7]:
# Run each script; its dataframe lands in the notebook's memory.
cycle_event_df = load_cycle_events()
cycle_df    = load_cycles()

Dropping 141 empty or constant columns:

  - plan_cryo_embryo
  - plan_cryo_egg
  - plan_ivf_zift
  - plan_ah
  - override_outcomes
  - reportable
  - checklist
  - surrogateid
  - plan_ivf_pgd
  - plan_ivf_icsi
  - plan_ivf_hatching
  - pat_instructions
  - input_pref_fields
  - outside_monitoring
  - min_stim
  - fin_status
  - plan_sperm
  - billing_status
  - cycleinsurance
  - accessionid
  - icsi_witness_other
  - eggdonorid
  - embryologist
  - paymentarranged
  - paymentarrangednote
  - psychevalnote
  - plan_embryo
  - plan_surrogate
  - paymentarrangedby
  - hist_ectopics
  - hist_abinduced
  - hist_abspontaneous
  - hist_preterm
  - hist_gravida
  - hist_fullterm
  - hist_lmp
  - prognosis
  - pg
  - children
  - sperm
  - cryo
  - max_encounter_date
  - cycle_notes
  - spermdonorid
  - psycheval
  - thaw_sperm_plan
  - thaw_sperm_id
  - plan_ivf_embryos
  - plan_gift_left_oocytes
  - thaw_sperm_status
  - thaw_sperm_done
  - thaw_embryo_plan
  - plan_gift_right_oocytes
  - outcome
  - partyid
  - coordinator
  - problemid
  - plan_stim
  - note
  - plan_options
  - research_approval_code
  - psychevalby
  - thaw_embryo_id
  - thaw_egg_status
  - thaw_egg_done
  - thaw_egg_plan
  - thaw_egg_id
  - thaw_embryo_done
  - thaw_embryo_status
  - fin_quote
  - embryology_note
  - planning_note
  - hist_stillbirth
  - hist_biochem
  - importid
  - financing_note
  - fin_package
  - no_pgt
  - import_emb_originalcycle
  - import_emb_freezingthawdat
  - dropdowncustomcategory
  - import_art_type
  - hist_ht
  - fin_claim
  - hist_part_surg_sterile
  - hist_wt
  - quote_id
  - financialsignon
  - financialsignby
  - chloe_treatment_external_id
  - secondchecklist_done
  - sart_clinic_id
  - chloe_treatment_id
  - labsignoffon
  - chloe_start_date
  - chloe_patient_external_id
  - labsignoffby
  - other_doctor
  - patientportal_viewedon
  - icsi_tech_other
  - insemination_tech_other
  - review_note_editedon
  - review_note
  - review_note_editedby
  - need_auth
  - need_quote
  - need_global
  - clinical_status
  - secondchecklist_doneby
  - plannedmonth
  - cycleboard_start
  - ocp_cutoff_date
  - ivf_meeting_date
  - cycleadditons
  - clinicalcomments
  - medicationsordered
  - ocp_start_date
  - spermproduction
  - financialcomment
  - cralert
  - aspiration_locked_on
  - aspiration_locked_by
  - birth_locked_on
  - birth_locked_by
  - culture_locked_on
  - culture_locked_by
  - insemination_locked_on
  - insemination_locked_by
  - overview_locked_on
  - overview_locked_by
  - pregnancy_locked_on
  - pregnancy_locked_by
  - transfer_locked_on
  - transfer_locked_by
  - main_note_lockedby
  - main_note_locked
  - plan_patientportal_releasedon
  - plan_patientportal_releasedby
  - patient_signature
  - patient_sigimg
  - patient_signedon

c:\Users\tamar.schaap\Projects\csv-data-prep\rpsd-nable-data-processing\scripts\processing.py:165: DtypeWarning: Columns (0: deletedon, 1: plan_sperm, 2: eggdonorid, 3: checklist_done, 4: incubator, 5: fin_status, 6: pat_instructions, 7: pregnancystart, 8: accessionid, 9: icsi_witness_other, 10: billing_status) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [8]:
cycle_event_df.shape, cycle_df.shape

((3591, 6), (9775, 48))

## 2. Merge df's from processing scripts

LEFT_KEY  = "cycleid"      # join key in response_df  (confirm exact name)
RIGHT_KEY = "id"           # join key in cycle_df

In [9]:
# merging by "cycleid" in cycle_event_df and "id" in cycle_df
merged_df = pd.merge(cycle_event_df, cycle_df, left_on="cycleid", right_on="id", how="left")

In [10]:
display(merged_df.head(20))

print(merged_df.shape)

,cycleid,label,eventdate,response_type,retrieval_date,trigger_date,id,sart_id,patid,partnerid,barcode,chloe_id,height,weight,bmi,addedby,status,closed,cycletype,schedulestart,cyclestart,cycleend,scheduleend,event_labels,doctor,plan_treatment,main_note,art_reason,cycle_name,cyclecoordinator,icsi_tech,icsi_witness,insemination_tech,hist_smoker,hist_pat_surg_sterile,hist_monthsattempting,manual_culturestart,planned_start_date,planned_retrieval_date,orig_scheduleend,edd,calc_basedate,calc_type,last_prospective_report_id,last_final_report_id,pgt_reason,pgt_type,last_final_report_date,eggsource_eligibility,spermsource_eligibility,planned_eggsource,planned_spermsource,end_reason,icsi_reason
0,c6e70948-17fb-4594-a3c3-657bff9f9557,STIM,2023-10-05,poor,NaN,NaN,c6e70948-17fb-4594-a3c3-657bff9f9557,n_8763,39942,39943.0,29115,4,170.18,75.922381,26.21,541,Canceled,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-09-03,2023-10-05,2023-10-13,2023-10-13,1=STIM&-32=LMP,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF Long Estrace w ADJ (no GH) + CC + PGT-A\nL...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: Long Estrace Gon...,541.0,NaN,NaN,NaN,0.0,-1.0,3.0,NaN,2023-09-03,2023-10-17,2024-01-16,NaN,NaN,NaN,512aa1ee-4840-4af4-91af-814a71fd1095,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,"Desired eSET, Elective PGT",PGT-A,2024-10-31 13:28:32.903198-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16587,16588,Low response,Laboratory routine
1,e11a96de-eb7e-480b-8c81-69c8b7be4e70,STIM,2023-05-19,poor,NaN,NaN,e11a96de-eb7e-480b-8c81-69c8b7be4e70,NaN,30470,30471.0,23210,9,162.56,68.220374,25.82,14,Completed,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-04-07,2023-05-19,2023-06-17,2023-06-17,1=STIM,4,31874673-6e93-4ec2-b175-a8e2cc4860af,IUI converted from Long Estrace low stim w/ ad...,ARTReason_6=on&ARTReason_6_DimOv=on&ARTReason_...,IUI converted from IVF,14.0,NaN,NaN,NaN,NaN,-1.0,1.0,NaN,2023-04-07,2023-05-10,2023-06-17,2024-02-22,2023-05-18,retrieval,NaN,NaN,"Desired eSET, Elective PGT",PGT-A,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,7115,7116,NaN,"PGT, Laboratory routine"
2,ce67cd1a-d9a4-448c-9d14-9d784683fa27,STIM,2023-06-16,poor,NaN,NaN,ce67cd1a-d9a4-448c-9d14-9d784683fa27,n_7401,38386,38387.0,25281,10,162.56,60.962887,23.07,66,Canceled,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-05-24,2023-06-16,2023-06-22,2023-06-22,1=STIM,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Long Estrace Menopur 225 100CC GH SD1 fresh sp...,ARTReason_1=on&ARTReason_6=on&ARTReason_6_DimO...,IVF: Freeze All - Autologous: Long Estrace Gon...,66.0,NaN,NaN,NaN,0.0,-1.0,1.0,NaN,2023-06-16,NaN,2023-10-06,NaN,NaN,NaN,b7e92107-fcdf-44f0-8eae-10b37d985a1d,0f955604-a115-43e8-b33a-ed725e2e4c11,Elective PGT,PGT-A,2024-10-30 11:32:44.530219-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,15031,15032,Low response,Laboratory routine
3,0554fe39-755c-4a1f-93cc-1ce7863c492e,STIM,2023-03-11,normal,2023-03-24,2023-03-22,0554fe39-755c-4a1f-93cc-1ce7863c492e,n_11545,40333,40334.0,21391,14,165.10,75.750016,27.79,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-02-18,2023-03-11,2023-04-01,2023-04-01,1=STIM&12=TRG&14=RET,7,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA standard stim no adj w/ PGT-A\nConsented ...,ARTReason_15=on,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,14.0,287.0,31.0,31.0,NaN,NaN,NaN,NaN,2023-02-17,2023-03-22,2023-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16978,16979,NaN,NaN
4,b6cc920b-2cd4-4ea5-9aac-1bce596f78b7,STIM,2023-09-02,normal,2023-09-16,2023-09-14,b6cc920b-2cd4-4ea5-9aac-1bce596f78b7,n_8453,37331,NaN,25611,16,157.48,59.239234,23.89,53,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-07-28,2023-09-02,2023-09-16,2023-09-16,1=STIM&-36=LMP&-21=%2BLH&13=TRG&15=RET,4,02672e1f-371b-433a-be83-8664dfe7412d,"MLEA SS (225/225) + TT, Egg Freeze (NO RT OVAR...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: MLEA Gonadot...,53.0,31.0,NaN,31.0,-98.0,-98.0,NaN,NaN,NaN,NaN,2023-12-10,NaN,NaN,NaN,1eabc273-8899-4ec7-a799-a4351dab51f8,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,NaN,NaN,2024-10-31 09:58:13.994399-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,NaN
5,482079e1-c78b-4e9a-bc4d-7b9c33fc6f18,STIM,2023-06-09,normal,2023-06-21,2023-06-19,482079e1-c78b-4e9a-bc4d-7b9c33fc6f18,n_7330,41917,41918.0,24820,24,170.18,69.218278,23.90,44,Canceled,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-05-05,2023-06-09,2023-06-12,2023-06-12,1=STIM&11=TRG&13=RET,3,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF MLEA (no Adj) + PGTA\nSCSA results pending...,ARTReason_1=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,44.0,NaN,NaN,NaN,-98.0,-98.0,12.0,NaN,2023-06-08,2023-06-21,2023-09-17,NaN,NaN,NaN,5395844f-06c8-443b-bda9-6823e14c4380,0f955604-a115-43e8-b33a-ed725e2e4c11,Desired eSET,PGT-A,2024-10-30 11:32:44.098187-07,NaN,NaN,NaN,NaN,Withdrawal Family,NaN
6,03705db5-51dc-47a5-91a7-a21cec4d9530,STIM,2023-03-24,normal,2023-04-08,2023-04-06,03705db5-51dc-47a5-91a7-a21cec4d9530,n_11558,39543,39544.0,21525,47,162.56,59.420671,22.49,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-03-06,2023-03-24,2023-08-16,2023-08-16,1=STIM&14=TRG&16=RET,10,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA standard stim w/ adj (NO GH) w/ PGT-A\nLa...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,14.0,39.0,36.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,2023-04-10,NaN,NaN,NaN,NaN,f8e68347-4bb2-48c1-bf1c-0c21dfe56231,NaN,NaN,2024-10-24 15:07:53.371454-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16188,16189,NaN,NaN
7,4c9c143b-aba9-4be5-a70f-32b5fac4f8b4,STIM,2023-05-08,normal,2023-05-27,2023-05-25,4c9c143b-aba9-4be5-a70f-32b5fac4f8b4,n_6967,40797,40798.0,23800,57,170.18,93.045514,32.13,55,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2023-05-08,2023-05-08,2023-05-29,2023-05-29,1=STIM&18=TRG&20=RET,4,4e625189-d13b-4ca1-9f4d-463506ae7a5f,RANDOM START / 300M / 300G / 5MG LET / NO ADJ ...,ARTReason_13=on&ARTReason_13_Specify=Transgend...,IVF: Freeze All - Autologous: Random Stim Start,55.0,32.0,31.0,32.0,NaN,-1.0,NaN,NaN,2023-05-08,NaN,2023-05-29,NaN,NaN,NaN,fe1e7ff6-cce8-484a-af10-1da47c6ed367,0f955604-a115-43e8-b33a-ed725e2e4c11,Elective PGT,PGT-A,2024-10-30 11:32:43.143242-07,Autologous/SIP Use Only Not Evaluated for Infe...,ELIGIBLE Donor,NaN,NaN,NaN,PGT
8,2b309714-83fa-4a8f-b193-97cbb9ba2f39,STIM,2023-11-15,normal,2023-11-27,2023-11-25,2b309714-83fa-4a8f-b193-97cbb9ba2f39,n_9115,23847,NaN,33874,2631,170.18,94.800918,32.73,1497,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2023-11-15,2023-11-15,2024-01-10,2024-01-10,1=STIM&11=TRG&13=RET,4,02672e1f-371b-433a-be83-8664dfe7412d,"Modified double lumen, consider leaving smalle...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: Random Stim ...,60.0,NaN,NaN,NaN,-98.0,-98.0,NaN,NaN,NaN,NaN,2024-03-29,NaN,NaN,NaN,923798f5-c632-4509-9f9e-7d71b8a89586,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,NaN,NaN,2024-10-31 13:28:35.141883-07,ELIGIBLE Donor,NaN,NaN,NaN,NaN,NaN
9,0b6ae4b4-fbd4-4429-b86d-12c4f41c6456,STIM,2023-06-28,normal,2023-07-10,2023-07-08,0b6ae4b4-fbd4-4429-b86d-12c4f41c6456,n_7593,29872,29873.0,25941,87,165.10,67.272364,24.68,66,Canceled,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-05-24,2023-06-28,2023-07-03,2023-07-03,1=STIM&11=TRG&13=RET,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA stand stim w/ CC + Adj PGTA Fresh sperm,ARTReason_8=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,66.0,NaN,NaN,NaN,0.0,-1.0,0.0,NaN,2023-06-28,NaN,2023-10-06,NaN,NaN,NaN,d1279e2b-d6c0-4457-b9d2-889d5766012f,0f955604-a115-43e8-b33a-ed725e2e4c11,Elective PGT,PGT-A,2024-10-30 11:32:45.048823-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,6517,6518,High response,NaN
10,9fec34dc-1d24-493c-bce9-b4dcc61adefe,STIM,2023-06-03,normal,2023-06-15,2023-06-13,9fec34dc-1d24-493c-bce9-b4dcc61adefe,n_11922,26176,NaN,24060,95,180.34,90.718582,27.89,53,Canceled,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-05-13,2023-06-03,2023-06-09,2023-06-09,1=STIM&11=TRG&13=RET,3,02672e1f-371b-433a-be83-8664dfe7412d,"MLEA SS + CC, + ADJ, EGG FREEZE\n**Pt requesti...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: IVF: MLEA Go...,53.0,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,2023-09-25,NaN,NaN,NaN,NaN,0f955604-a115-43e8-b33a-ed725e2e4c11,NaN,NaN,2024-10-30 11:32:43.917363-07,NaN,NaN,NaN,NaN,Low response,NaN
11,defaf1aa-cf31-421f-91d5-85bf57821021,STIM,2023-05-28,normal,2023-06-09,2023-06-07,defaf1aa-cf31-421f-91d5-85bf57821021,n_7228,41787,41821.0,23833,96,160.02,50.797870,19.84,14,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-05-10,2023-05-28,2023-06-28,2023-06-28,1=STIM&11=TRG&13=RET,9,4e625189-d13b-4ca1-9f4d-463506ae7a5f,BCPA standard stim w/ dexa only w/ PGT-A\nLab ...,ARTReason_15=on,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,14.0,32.0,287.0,32.0,NaN,NaN,NaN,NaN,2023-05-10,NaN,2023-07-01,NaN,NaN,NaN,NaN,0f955604-a115-43e8-b33a-ed725e2e4c11,"Desired eSET, Elective PGT",PGT-A,2024-10-30 11:32:43.627231-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,18432,18466,NaN,"PGT, Laboratory routine"
12,e64378d4-aed0-4974-9985-991c7acc2d35,STIM,2023-12-28,normal,2024-01-09,2024-01-07,e64378d4-aed0-4974-9985-991c7acc2d35,n_9347,45950,NaN,35577,118,165.10,61.325761,22.50,60,Canceled,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-12-28,2023-12-28,2023-12-28,2023-12-28,1=STIM&11=TRG&13=RET,43,02672e1f-371b-433a-be83-8664dfe7412d,BCP ANT SS with CC no adj EGG FREEZE,ARTReason_13=on&ARTReason_13_Specify=++Fertili...,Oocyte Freeze Cycle - Autologous: BCPA Gonadot...,60.0,NaN,NaN,NaN,0.0,-1.0,0.0,NaN,2023-12-28,NaN,2024-05-11,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,NaN,NaN,2024-10-31 13:28:36.799096-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,22595,NaN,Low response,NaN
13,b3081467-6418-4d4a-bce1-9d5e0a281d8f,STIM,2022-06-24,normal,2022-07-06,2022-07-04,b3081467-6418-4d4a-bce1-9d5e0a281d8f,n_3461,22600,22861.0,11625,127,157.48,77.836543,31.39,63,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2022-05-13,2022-06-24,2022-07-06,2022-07-06,1=STIM&11=TRG&13=RET,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF BCP + CLOMID +ADJ +PGTA (patient and partn...,ARTReason_7=on&ARTReason_11=on&ARTReason_11_Re...,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,63.0,39.0,309.0,39.0,-98.0,-98.0,NaN,NaN,2022-06-24,NaN,2022-09-25,NaN,NaN,NaN,NaN,a166e5c1-cf00-43b1-bfa3-a278f433d945,Aneuploidy Screening for Advanced Age,NaN,2023-11-17 14:06:18.520897-08,ELIGIBLE Donor,ELIGIBLE Donor,6322356,33003708,NaN,NaN
14,d00b503b-8d54-4ea0-97dd-24de5b683ea7,STIM,2023-12-02,normal,2023-12-14,2023-12-12,d00b503b-8d54-4ea0-97dd-24de5b683ea7,n_9227,45547,NaN,33465,69,165.10,64.319475,23.60,60,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-12-02,2023-12-02,2024-02-13,2024-02-13,1=STIM&11=TRG&13=RET,43,02672e1f-371b-433a-be83-8664dfe7412d,12-15-23: Spoke to pt and informed her that we...,ARTReason_7=on,Oocyte Freeze Cycle - Autologous: BCPA Gonadot...,60.0,NaN,NaN,NaN,0.0,-1.0,0.0,NaN,NaN,NaN,2024-04-15,NaN,NaN,NaN,7830bd75-3e84-44fc-b9c1-5b57706ca1b1,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,NaN,NaN,2024-10-31 13:28:36.365821-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,22192,NaN,NaN,NaN
15,adc6b8ae-5a69-41eb-a20b-7b2abd24f05e,STIM,2023-04-06,poor,NaN,NaN,adc6b8ae-5a69-41eb-a20b-7b2abd24f05e,n_6607,37132,37133.0,22678,139,170.18,74.389237,25.69,55,Canceled,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-02-23,2023-04-06,2023-04-12,2023-04-12,1=STIM&-42=LMP,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA / STANDARD / 375M / 300F / 100CC / GH FRO...,ARTReason_6=on&ARTReason_6_DimOv=on&ARTReason_...,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,55.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,2023-04-06,NaN,2023-04-12,NaN,NaN,NaN,41390b5d-4329-4bcc-a94e-86f1f46ccbe7,9f25ef68-4faf-487d-8f11-de8432f7e81c,Elective PGT,PGT-A,2024-10-24 17:52:10.181127-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,13777,13778,Low response,PGT
16,358a9bfa-06fb-4957-bcbb-224258b420aa,STIM,2021-09-16,poor,NaN,NaN,358a9bfa-06fb-4957-bcbb-224258b420aa,n_28,3,6.0,11253,142,NaN,NaN,NaN,14,Active,False,ac36dd51-7809-4975-83de-48cda51987f5,2021-09-05,2021-09-16,NaN,2022-01-18,1=STIM,1,4e625189-d13b-4ca1-9f4d-463506ae7a5f,NaN,NaN,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,0.0,39.0,NaN,39.0,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,4d387ea1-f2a4-40e7-b5b1-a1156e058666,STIM,2020-11-03,poor,NaN,NaN,4d387ea1-f2a4-40e7-b5b1-a1156e058666,n_15,3,6.0,10105,147,NaN,NaN,NaN,14,Active,False,ac36dd51-7809-4975-83de-48cda51987f5,2020-10-01,2020-11-03,NaN,2021-02-13,1=STIM,1,4e625189-d13b-4ca1-9f4d-463506ae7a5f,NaN,NaN,IVF: Freeze All - Autologous: IVF: BCP Gonadot...,57.0,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,2020-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,5bbb8530-832a-458c-930d-a52a56f646db,STIM,2024-01-12,normal,2024-01-24,2024-01-22,5bbb8530-832a-458c-930d-a52a56f646db,n_9455,23040,NaN,38217,1298,152.40,53.523963,23.05,60,Canceled,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2024-01-11,2024-01-12,2024-01-12,2024-01-12,NaN,3,02672e1f-371b-433a-be83-8664dfe7412d,NaN,ARTReason_7=on,Oocyte Freeze Cycle - Autologous: Random Stim ...,60.0,NaN,NaN,NaN,-98.0,-98.0,NaN,NaN,2024-01-12,NaN,2024-05-25,NaN,NaN,NaN,02313b6c-e621-4a6d-8407-5db912ef1698,2a01e319-f165-4087-bfb7-0e8357ccf4ec,NaN,NaN,2025-11-05 19:16:12.444954-08,NaN,NaN,NaN,NaN,Low response,NaN
19,8060c25c-62c8-4f66-8b99-8fb57d328cef,STIM,2023-04-06,normal,2023-04-18,2023-04-16,8060c25c-62c8-4f66-8b99-8fb57d328cef,n_11788,37000,37001.0,22344,153,162.56,92.532954,35.02,14,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-03-14,2023-04-06,2023-06-14,2023-06-14,1=STIM&11=TRG&13=RET,10,4e625189-d13b-4ca1-9f4d-463506ae7a5f,BCPA standard stim w/ dexa w/ PGT-A w/ frozen ...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,14.0,287.0,31.0,287.0,NaN,NaN,NaN,NaN,2023-03-14,2023-04-18,2023-07-27,NaN,NaN,NaN,NaN,9f25ef68-4faf-487d-8f11-de8432f7e81c,"Elective PGT, Desired eSET",PGT-A,2024-10-24 17:52:10.187566-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,13645,13646,NaN,"PGT, Laboratory routine"

(3591, 54)

In [11]:
display(merged_df.head(5))

,cycleid,label,eventdate,response_type,retrieval_date,trigger_date,id,sart_id,patid,partnerid,barcode,chloe_id,height,weight,bmi,addedby,status,closed,cycletype,schedulestart,cyclestart,cycleend,scheduleend,event_labels,doctor,plan_treatment,main_note,art_reason,cycle_name,cyclecoordinator,icsi_tech,icsi_witness,insemination_tech,hist_smoker,hist_pat_surg_sterile,hist_monthsattempting,manual_culturestart,planned_start_date,planned_retrieval_date,orig_scheduleend,edd,calc_basedate,calc_type,last_prospective_report_id,last_final_report_id,pgt_reason,pgt_type,last_final_report_date,eggsource_eligibility,spermsource_eligibility,planned_eggsource,planned_spermsource,end_reason,icsi_reason
0,c6e70948-17fb-4594-a3c3-657bff9f9557,STIM,2023-10-05,poor,NaN,NaN,c6e70948-17fb-4594-a3c3-657bff9f9557,n_8763,39942,39943.0,29115,4,170.18,75.922381,26.21,541,Canceled,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-09-03,2023-10-05,2023-10-13,2023-10-13,1=STIM&-32=LMP,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF Long Estrace w ADJ (no GH) + CC + PGT-A\nL...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: Long Estrace Gon...,541.0,NaN,NaN,NaN,0.0,-1.0,3.0,NaN,2023-09-03,2023-10-17,2024-01-16,NaN,NaN,NaN,512aa1ee-4840-4af4-91af-814a71fd1095,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,"Desired eSET, Elective PGT",PGT-A,2024-10-31 13:28:32.903198-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16587,16588,Low response,Laboratory routine
1,e11a96de-eb7e-480b-8c81-69c8b7be4e70,STIM,2023-05-19,poor,NaN,NaN,e11a96de-eb7e-480b-8c81-69c8b7be4e70,NaN,30470,30471.0,23210,9,162.56,68.220374,25.82,14,Completed,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-04-07,2023-05-19,2023-06-17,2023-06-17,1=STIM,4,31874673-6e93-4ec2-b175-a8e2cc4860af,IUI converted from Long Estrace low stim w/ ad...,ARTReason_6=on&ARTReason_6_DimOv=on&ARTReason_...,IUI converted from IVF,14.0,NaN,NaN,NaN,NaN,-1.0,1.0,NaN,2023-04-07,2023-05-10,2023-06-17,2024-02-22,2023-05-18,retrieval,NaN,NaN,"Desired eSET, Elective PGT",PGT-A,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,7115,7116,NaN,"PGT, Laboratory routine"
2,ce67cd1a-d9a4-448c-9d14-9d784683fa27,STIM,2023-06-16,poor,NaN,NaN,ce67cd1a-d9a4-448c-9d14-9d784683fa27,n_7401,38386,38387.0,25281,10,162.56,60.962887,23.07,66,Canceled,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-05-24,2023-06-16,2023-06-22,2023-06-22,1=STIM,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Long Estrace Menopur 225 100CC GH SD1 fresh sp...,ARTReason_1=on&ARTReason_6=on&ARTReason_6_DimO...,IVF: Freeze All - Autologous: Long Estrace Gon...,66.0,NaN,NaN,NaN,0.0,-1.0,1.0,NaN,2023-06-16,NaN,2023-10-06,NaN,NaN,NaN,b7e92107-fcdf-44f0-8eae-10b37d985a1d,0f955604-a115-43e8-b33a-ed725e2e4c11,Elective PGT,PGT-A,2024-10-30 11:32:44.530219-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,15031,15032,Low response,Laboratory routine
3,0554fe39-755c-4a1f-93cc-1ce7863c492e,STIM,2023-03-11,normal,2023-03-24,2023-03-22,0554fe39-755c-4a1f-93cc-1ce7863c492e,n_11545,40333,40334.0,21391,14,165.10,75.750016,27.79,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-02-18,2023-03-11,2023-04-01,2023-04-01,1=STIM&12=TRG&14=RET,7,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA standard stim no adj w/ PGT-A\nConsented ...,ARTReason_15=on,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,14.0,287.0,31.0,31.0,NaN,NaN,NaN,NaN,2023-02-17,2023-03-22,2023-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16978,16979,NaN,NaN
4,b6cc920b-2cd4-4ea5-9aac-1bce596f78b7,STIM,2023-09-02,normal,2023-09-16,2023-09-14,b6cc920b-2cd4-4ea5-9aac-1bce596f78b7,n_8453,37331,NaN,25611,16,157.48,59.239234,23.89,53,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-07-28,2023-09-02,2023-09-16,2023-09-16,1=STIM&-36=LMP&-21=%2BLH&13=TRG&15=RET,4,02672e1f-371b-433a-be83-8664dfe7412d,"MLEA SS (225/225) + TT, Egg Freeze (NO RT OVAR...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: MLEA Gonadot...,53.0,31.0,NaN,31.0,-98.0,-98.0,NaN,NaN,NaN,NaN,2023-12-10,NaN,NaN,NaN,1eabc273-8899-4ec7-a799-a4351dab51f8,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,NaN,NaN,2024-10-31 09:58:13.994399-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,NaN

## Filtering dataset

1) cases that do not have height/weight included
2) cases in which cancellation was immediately after stim start (not enough time to determine poor response to stim)

In [12]:
# There are plenty of test records in nAble - maybe ask Grant to filter those out. For now, filtering to get rid of NA in weight and height will get rid of those cases
merged_df = merged_df[merged_df["weight"].notna() & merged_df["height"].notna()]

print(merged_df.shape)

(3535, 54)

In [13]:
# Deleting rows where the cyclestart and the cycleend are less than or equal to 2 days apart
merged_df["cyclestart"] = pd.to_datetime(merged_df["cyclestart"])
merged_df["cycleend"]   = pd.to_datetime(merged_df["cycleend"])

merged_df["duration"] = (merged_df["cycleend"] - merged_df["cyclestart"]).dt.days

# cycles are only cancelled for poor response at at least 5-6 days in and completed cycles don't trigger before day 8, so getting rid of cycles less than 5 days
merged_df = merged_df[merged_df["duration"] >= 5]

In [14]:
print(merged_df.shape)

(2993, 55)

In [13]:
"""
# Deleting rows where the cyclestart and the cycleend are less than or equal to 2 days apart

# turn cyclestart and cycleend into datetime objects
merged_df["cyclestart"] = pd.to_datetime(merged_df["cyclestart"])
merged_df["cycleend"] = pd.to_datetime(merged_df["cycleend"])

# now applying the filter
merged_df = merged_df[(merged_df["cyclestart"] - merged_df["cycleend"]).dt.days >= 2]

# also getting rid of cycles in which the cycleend is before the cyclestart (so STIM never started)
merged_df =  merged_df[(merged_df["cyclestart"] - merged_df["cycleend"]).dt.days <= 0]
"""

'\n# Deleting rows where the cyclestart and the cycleend are less than or equal to 2 days apart\n\n# turn cyclestart and cycleend into datetime objects\nmerged_df["cyclestart"] = pd.to_datetime(merged_df["cyclestart"])\nmerged_df["cycleend"] = pd.to_datetime(merged_df["cycleend"])\n\n# now applying the filter\nmerged_df = merged_df[(merged_df["cyclestart"] - merged_df["cycleend"]).dt.days >= 2]\n\n# also getting rid of cycles in which the cycleend is before the cyclestart (so STIM never started)\nmerged_df =  merged_df[(merged_df["cyclestart"] - merged_df["cycleend"]).dt.days <= 0]\n'

In [15]:
# Getting rid of rows with NA in "sart_id" since those are not IVF cycles (or they are IVF cycles that are unfinished)
merged_df = merged_df.dropna(subset=["sart_id"])

In [16]:
print(merged_df.shape)

(2633, 55)

In [15]:
# sort all values of "duration" from smallest to largest
merged_df = merged_df.sort_values(by="duration")

In [ ]:
#manual entering of missing dates:
# if cycleid = 63799a3d-c145-40b5-9234-b2369dacb25f, then retrieval_date = 2021-11-09

# if cycleid = "4206ba52-6b2a-4037-acb4-4c9cff348d31", then retrieval_date = 2022-04-26

# if sart_id = "n_2478", then response_type = "patient_dropped"

# if sart_id = "n_266", then retrieval_date = 2021-12-16

# if sart_id = "n_99", then retrieval_date = 2021-11-16

# if sart_id = "271", then retrieval_date = 2021-12-17 (patid 23482)

In [17]:
# converting trigger_date and retrieval_date to datetime
merged_df["trigger_date"] = pd.to_datetime(merged_df["trigger_date"], errors="coerce")
merged_df["retrieval_date"] = pd.to_datetime(merged_df["retrieval_date"], errors="coerce")

# if status == "Completed" and retrieval_date is NA, then retrieval_date = trigger_date + 2 days
merged_df.loc[(merged_df["status"] == "Completed") & (merged_df["retrieval_date"].isna()), "retrieval_date"] = merged_df["trigger_date"] + pd.Timedelta(days=2)

# if status == "Completed" and trigger_date is NA, then trigger_date = retrieval_date - 2 days
merged_df.loc[(merged_df["status"] == "Completed") & (merged_df["trigger_date"].isna()), "trigger_date"] = merged_df["retrieval_date"] - pd.Timedelta(days=2)

In [18]:
#display(merged_df.head(30))
print(merged_df.shape) # look into case: e11a96de-eb7e-480b-8c81-69c8b7be4e70 poor but not cancelled?

(2633, 55)

In [19]:
# counting status
merged_df["status"].value_counts()

status
Completed    2425
Canceled      208
Name: count, dtype: int64

In [22]:
# looking at completed cycles
display(merged_df[merged_df["status"] == "Completed"].head(30))

,cycleid,label,eventdate,response_type,retrieval_date,trigger_date,id,sart_id,patid,partnerid,barcode,chloe_id,height,weight,bmi,addedby,status,closed,cycletype,schedulestart,cyclestart,cycleend,scheduleend,event_labels,doctor,plan_treatment,main_note,art_reason,cycle_name,cyclecoordinator,icsi_tech,icsi_witness,insemination_tech,hist_smoker,hist_pat_surg_sterile,hist_monthsattempting,manual_culturestart,planned_start_date,planned_retrieval_date,orig_scheduleend,edd,calc_basedate,calc_type,last_prospective_report_id,last_final_report_id,pgt_reason,pgt_type,last_final_report_date,eggsource_eligibility,spermsource_eligibility,planned_eggsource,planned_spermsource,end_reason,icsi_reason,duration
3,0554fe39-755c-4a1f-93cc-1ce7863c492e,STIM,2023-03-11,normal,2023-03-24,2023-03-22,0554fe39-755c-4a1f-93cc-1ce7863c492e,n_11545,40333,40334.0,21391,14,165.10,75.750016,27.79,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-02-18,2023-03-11,2023-04-01,2023-04-01,1=STIM&12=TRG&14=RET,7,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA standard stim no adj w/ PGT-A\nConsented ...,ARTReason_15=on,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,14.0,287.0,31.0,31.0,NaN,NaN,NaN,NaN,2023-02-17,2023-03-22,2023-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16978,16979,NaN,NaN,21.0
4,b6cc920b-2cd4-4ea5-9aac-1bce596f78b7,STIM,2023-09-02,normal,2023-09-16,2023-09-14,b6cc920b-2cd4-4ea5-9aac-1bce596f78b7,n_8453,37331,NaN,25611,16,157.48,59.239234,23.89,53,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-07-28,2023-09-02,2023-09-16,2023-09-16,1=STIM&-36=LMP&-21=%2BLH&13=TRG&15=RET,4,02672e1f-371b-433a-be83-8664dfe7412d,"MLEA SS (225/225) + TT, Egg Freeze (NO RT OVAR...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: MLEA Gonadot...,53.0,31.0,NaN,31.0,-98.0,-98.0,NaN,NaN,NaN,NaN,2023-12-10,NaN,NaN,NaN,1eabc273-8899-4ec7-a799-a4351dab51f8,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,NaN,NaN,2024-10-31 09:58:13.994399-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,NaN,14.0
6,03705db5-51dc-47a5-91a7-a21cec4d9530,STIM,2023-03-24,normal,2023-04-08,2023-04-06,03705db5-51dc-47a5-91a7-a21cec4d9530,n_11558,39543,39544.0,21525,47,162.56,59.420671,22.49,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-03-06,2023-03-24,2023-08-16,2023-08-16,1=STIM&14=TRG&16=RET,10,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA standard stim w/ adj (NO GH) w/ PGT-A\nLa...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,14.0,39.0,36.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,2023-04-10,NaN,NaN,NaN,NaN,f8e68347-4bb2-48c1-bf1c-0c21dfe56231,NaN,NaN,2024-10-24 15:07:53.371454-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,16188,16189,NaN,NaN,145.0
7,4c9c143b-aba9-4be5-a70f-32b5fac4f8b4,STIM,2023-05-08,normal,2023-05-27,2023-05-25,4c9c143b-aba9-4be5-a70f-32b5fac4f8b4,n_6967,40797,40798.0,23800,57,170.18,93.045514,32.13,55,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2023-05-08,2023-05-08,2023-05-29,2023-05-29,1=STIM&18=TRG&20=RET,4,4e625189-d13b-4ca1-9f4d-463506ae7a5f,RANDOM START / 300M / 300G / 5MG LET / NO ADJ ...,ARTReason_13=on&ARTReason_13_Specify=Transgend...,IVF: Freeze All - Autologous: Random Stim Start,55.0,32.0,31.0,32.0,NaN,-1.0,NaN,NaN,2023-05-08,NaN,2023-05-29,NaN,NaN,NaN,fe1e7ff6-cce8-484a-af10-1da47c6ed367,0f955604-a115-43e8-b33a-ed725e2e4c11,Elective PGT,PGT-A,2024-10-30 11:32:43.143242-07,Autologous/SIP Use Only Not Evaluated for Infe...,ELIGIBLE Donor,NaN,NaN,NaN,PGT,21.0
8,2b309714-83fa-4a8f-b193-97cbb9ba2f39,STIM,2023-11-15,normal,2023-11-27,2023-11-25,2b309714-83fa-4a8f-b193-97cbb9ba2f39,n_9115,23847,NaN,33874,2631,170.18,94.800918,32.73,1497,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2023-11-15,2023-11-15,2024-01-10,2024-01-10,1=STIM&11=TRG&13=RET,4,02672e1f-371b-433a-be83-8664dfe7412d,"Modified double lumen, consider leaving smalle...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: Random Stim ...,60.0,NaN,NaN,NaN,-98.0,-98.0,NaN,NaN,NaN,NaN,2024-03-29,NaN,NaN,NaN,923798f5-c632-4509-9f9e-7d71b8a89586,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,NaN,NaN,2024-10-31 13:28:35.141883-07,ELIGIBLE Donor,NaN,NaN,NaN,NaN,NaN,56.0
11,defaf1aa-cf31-421f-91d5-85bf57821021,STIM,2023-05-28,normal,2023-06-09,2023-06-07,defaf1aa-cf31-421f-91d5-85bf57821021,n_7228,41787,41821.0,23833,96,160.02,50.797870,19.84,14,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-05-10,2023-05-28,2023-06-28,2023-06-28,1=STIM&11=TRG&13=RET,9,4e625189-d13b-4ca1-9f4d-463506ae7a5f,BCPA standard stim w/ dexa only w/ PGT-A\nLab ...,ARTReason_15=on,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,14.0,32.0,287.0,32.0,NaN,NaN,NaN,NaN,2023-05-10,NaN,2023-07-01,NaN,NaN,NaN,NaN,0f955604-a115-43e8-b33a-ed725e2e4c11,"Desired eSET, Elective PGT",PGT-A,2024-10-30 11:32:43.627231-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,18432,18466,NaN,"PGT, Laboratory routine",31.0
13,b3081467-6418-4d4a-bce1-9d5e0a281d8f,STIM,2022-06-24,normal,2022-07-06,2022-07-04,b3081467-6418-4d4a-bce1-9d5e0a281d8f,n_3461,22600,22861.0,11625,127,157.48,77.836543,31.39,63,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2022-05-13,2022-06-24,2022-07-06,2022-07-06,1=STIM&11=TRG&13=RET,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF BCP + CLOMID +ADJ +PGTA (patient and partn...,ARTReason_7=on&ARTReason_11=on&ARTReason_11_Re...,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,63.0,39.0,309.0,39.0,-98.0,-98.0,NaN,NaN,2022-06-24,NaN,2022-09-25,NaN,NaN,NaN,NaN,a166e5c1-cf00-43b1-bfa3-a278f433d945,Aneuploidy Screening for Advanced Age,NaN,2023-11-17 14:06:18.520897-08,ELIGIBLE Donor,ELIGIBLE Donor,6322356,33003708,NaN,NaN,12.0
14,d00b503b-8d54-4ea0-97dd-24de5b683ea7,STIM,2023-12-02,normal,2023-12-14,2023-12-12,d00b503b-8d54-4ea0-97dd-24de5b683ea7,n_9227,45547,NaN,33465,69,165.10,64.319475,23.60,60,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-12-02,2023-12-02,2024-02-13,2024-02-13,1=STIM&11=TRG&13=RET,43,02672e1f-371b-433a-be83-8664dfe7412d,12-15-23: Spoke to pt and informed her that we...,ARTReason_7=on,Oocyte Freeze Cycle - Autologous: BCPA Gonadot...,60.0,NaN,NaN,NaN,0.0,-1.0,0.0,NaN,NaN,NaN,2024-04-15,NaN,NaN,NaN,7830bd75-3e84-44fc-b9c1-5b57706ca1b1,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,NaN,NaN,2024-10-31 13:28:36.365821-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,22192,NaN,NaN,NaN,73.0
19,8060c25c-62c8-4f66-8b99-8fb57d328cef,STIM,2023-04-06,normal,2023-04-18,2023-04-16,8060c25c-62c8-4f66-8b99-8fb57d328cef,n_11788,37000,37001.0,22344,153,162.56,92.532954,35.02,14,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-03-14,2023-04-06,2023-06-14,2023-06-14,1=STIM&11=TRG&13=RET,10,4e625189-d13b-4ca1-9f4d-463506ae7a5f,BCPA standard stim w/ dexa w/ PGT-A w/ frozen ...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,14.0,287.0,31.0,287.0,NaN,NaN,NaN,NaN,2023-03-14,2023-04-18,2023-07-27,NaN,NaN,NaN,NaN,9f25ef68-4faf-487d-8f11-de8432f7e81c,"Elective PGT, Desired eSET",PGT-A,2024-10-24 17:52:10.187566-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,13645,13646,NaN,"PGT, Laboratory routine",69.0
25,33264630-3f16-47b5-af1c-e918b5b321f5,STIM,2023-04-28,normal,2023-05-11,2023-05-09,33264630-3f16-47b5-af1c-e918b5b321f5,n_6867,40300,40301.0,23403,164,167.64,66.043128,23.50,44,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-04-06,2023-04-28,2023-06-30,2023-06-30,1=STIM&14=RET&12=TRG,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF MLEA SS + Adj + DEXA (NO CLOMID) + GH DAY ...,ARTReason_1=on&ARTReason_1_OtherMaleFactor=on&...,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,44.0,39.0,NaN,31.0,NaN,-1.0,1.0,NaN,2023-03-22,NaN,2023-08-19,NaN,NaN,NaN,af9e380f-4828-42de-8bed-1bfcad0556aa,NaN,Desired eSET,NaN,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,63.0
33,9b807cfd-03f6-46ba-b745-8f8f703471ae,STIM,2022-04-18,poor,NaT,NaT,9b807cfd-03f6-46ba-b745-8f8f703471ae,n_7799,28194,28195.0,11040,178,157.48,67.585344,27.25,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2022-03-28,2022-04-18,2023-06-01,2023-06-01,1=STIM,9,4e625189-d13b-4ca1-9f4d-463506ae7a5f,KPRPMG2022-2\nMLEA standard stim w/ clomid w/ ...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,0.0,39.0,37.0,39.0,NaN,NaN,NaN,NaN,2022-03-28,NaN,2022-08-10,NaN,NaN,NaN,NaN,a166e5c1-cf00-43b1-bfa3-a278f433d945,"Aneuploidy Screening for Advanced Age, Electiv...",PGT-A,2023-11-17 14:06:16.5656-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,PATIENT,PARTNER,NaN,"PGT, Laboratory routine",409.0
34,87a248a8-c4a1-4842-bc54-efb91c02ef4a,STIM,2021-12-31,poor,NaT,NaT,87a248a8-c4a1-4842-bc54-efb91c02ef4a,n_2156,24828,24829.0,10445,180,160.02,55.882646,22.00,41,Completed,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2021-12-22,2021-12-31,2022-01-14,2022-01-14,1=STIM,7,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF LONG ESTRACE + ADJ + CC +PGT-A\nER: Reques...,ARTReason_13=on&ARTReason_13_Specify=DOR,IVF: Freeze All - Autologous: IVF: Long Estrac...,41.0,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,2021-11-22,2022-01-11,2022-05-06,NaN,NaN,NaN,NaN,NaN,Aneuploidy Screening for Advanced Age,PGT-A,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,patient,partner,NaN,Laboratory routine,14.0
35,3373e6cb-5fec-45ec-bb43-16fe94776e3e,STIM,2023-08-19,normal,2023-08-31,2023-08-29,3373e6cb-5fec-45ec-bb43-16fe94776e3e,n_8313,43767,43768.0,26901,3214,165.10,61.144324,22.43,1563,Completed,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-07-31,2023-08-19,2023-11-03,2023-11-03,1=STIM&13=RET&11=TRG,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF Long Estrace SS + ADJ + CC no GH + PGTA\nC...,ARTReason_15=on,IVF: Freeze All - Autologous: Long Estrace Gon...,1563.0,37.0,309.0,37.0,0.0,-1.0,5.0,NaN,2023-07-22,2023-09-07,2023-11-27,NaN,NaN,NaN,4787ecdd-0547-4dfd-8cf8-043762dd9941,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,Aneuploidy Screening for Advanced Age,PGT-A,2024-10-31 09:58:13.537485-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,20412,20413,NaN,Laboratory routine,76.0
37,fa3574ce-b1b2-440e-a60b-9c4f0c44e4c9,STIM,2023-06-16,poor,NaT,NaT,fa3574ce-b1b2-440e-a60b-9c4f0c44e4c9,n_11935,27047,27048.0,22876,188,167.64,67.313188,23.95,53,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-05-24,2023-06-16,2023-06-28,2023-06-28,1=STIM,5,02672e1f-371b-433a-be83-8664dfe7412d,"MLEA LOW (225M/50CC) + Adj, GH on SD1, EGG FRE...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: IVF: MLEA Go...,53.0,NaN,NaN,NaN,-98.0,-1.0,1.0,NaN,NaN,NaN,2023-10-06,NaN,NaN,NaN,NaN,5fa03fd6-3bb7-4417-aa35-fe6a8953865f,NaN,NaN,2024-10-30 12:55:46.630403-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,NaN,12.0
38,38c71db7-9055-4e5c-8755-6b4eab438d06,STIM,2023-07-11,normal,2023-07-26,2023-07-24,38c71db7-9055-4e5c-8755-6b4eab438d06,n_7692,41070,42087.0,26310,193,154.94,50.893124,21.20,70,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-05-02,2023-07-11,2023-08-31,2023-08-31,1=STIM&-34=%2BLH&16=RET&14=TRG,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"MLEA. No T, 225/225/100, Partner Fresh sperm, ...",ARTReason_7=on&ARTReason_13=on&ARTReason_13_Sp...,IVF: Freeze All - Autologous: MLEA Gonadotropi...,70.0,39.0,309.0,39.0,0.0,-1.0,0.0,NaN,2023-05-02,NaN,2023-09-14,NaN,NaN,NaN,76362e82-fc05-4e68-a727-5d1353b9fe5a,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,Elective PGT,PGT-A,2024-10-31 09:58:12.028084-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,17715,18732,NaN,Laboratory routine,51.0
39,38e05f3b-7f78-49ec-8901-6dd5b1294b70,STIM,2023-10-15,normal,2023-10-28,2023-10-26,38e05f3b-7f78-49ec-8901-6dd5b1294b70,n_8823,46475,46476.0,29373,201,167.64,63.498471,22.60,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-09-07,2023-10-15,2023-11-06,2023-11-06,1=STIM&-38=LMP&12=TRG&14=RET,7,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA standard stim no adj w/ PGT-A (first IVF ...,ARTReason_15=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,14.0,287.0,31.0,287.0,-98.0,-98.0,NaN,NaN,2023-09-05,2023-10-25,2023-11-05,NaN,NaN,NaN,a4a37bd6-5e35-417b-9a24-b77adb6cbb9d,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,"Elective PGT, Desired eSET",PGT-A,2024-10-31 13:28:33.270167-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,23120,23121,NaN,"PGT, Laboratory routine",22.0
40,3beca621-0731-43f5-97ff-6bf34d1c0bee,STIM,2023-10-20,?,2023-11-01,2023-10-30,3beca621-0731-43f5-97ff-6bf34d1c0bee,n_8885,43237,43238.0,31490,4060,157.48,53.433245,21.55,144,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-09-08,2023-10-20,2023-11-14,2023-11-14,1=STIM&11=TRG,4,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA SS no ADJ + PGTA \nFresh Sperm / Consents...,ARTReason_8=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,60.0,32.0,309.0,32.0,-98.0,-98.0,21.0,NaN,NaN,NaN,2024-01-21,NaN,NaN,NaN,9b03d9eb-208d-4500-a385-15e7572593e4,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Elective PGT,NaN,2024-10-31 13:28:33.530235-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,Laboratory routine,25.0
41,13abdadb-53c2-40a8-b092-04102e5d7c2d,STIM,2023-07-13,normal,2023-07-26,2023-07-24,13abdadb-53c2-40a8-b092-04102e5d7c2d,n_11996,42185,42186.0,25055,212,175.26,66.678158,21.71,541,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-06-01,2023-07-12,2023-08-16,2023-08-16,2=STIM&13=TRG&15=RET,9,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF MLEA SS + ADJ + CC (previous IVF cycles (#...,ARTReason_13=on&ARTReason_13_Specify=AMA,IVF: Freeze All - Autologous: MLEA Gonadotropi...,14.0,39.0,NaN,39.0,-98.0,-98.0,NaN,NaN,2023-06-01,2023-07-24,2023-08-15,NaN,NaN,NaN,NaN,NaN,"Desired eSET, Elective PGT",PGT-A,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,18830,18831,NaN,"PGT, Laboratory routine",35.0
42,a94a82f5-5e80-4696-b9ec-e9e4532f46b6,STIM,2023-04-28,normal,2023-05-11,2023-05-09,a94a82f5-5e80-4696-b9ec-e9e4532f46b6,n_6866,39640,39641.0,22773,216,162.56,55.791928,21.11,53,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-04-07,2023-04-28,2023-05-17,2023-05-17,1=STIM&-21=LMP&12=TRG&14=RET,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI, CC, AH, PGT-A and FRZ at blast...",ARTReason_7=on,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,53.0,37.0,287.0,37.0,NaN,-1.0,NaN,NaN,NaN,NaN,2023-08-20,NaN,NaN,NaN,af9e380f-4828-42de-8bed-1bfcad0556aa,NaN,NaN,NaN,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,Partner,NaN,NaN,19.0
43,3a42b032-1a05-4bf9-ba49-11dc90161277,STIM,2023-07-15,normal,2023-07-27,2023-07-25,3a42b032-1a05-4bf9-ba49-11dc90161277,n_8160,44434,44435.0,26537,222,152.40,66.678158,28.71,14,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2023-07-15,2023-07-15,2023-07-27,2023-07-27,1=STIM&11=TRG&13=RET,7,02672e1f-371b-433a-be83-8664dfe7412d,Random start standard stim w/ LET no adj (ONCO...,ARTReason_13=on&ARTReason_13_Specify=cancer+tr...,Oocyte Freeze Cycle - Autologous: Random Stim ...,14.0,NaN,NaN,NaN,-98.0,-98.0,NaN,NaN,2023-07-15,NaN,2023-08-01,NaN,NaN,NaN,NaN,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,NaN,NaN,2024-10-31 09:58:12.127888-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,21079,NaN,NaN,NaN,12.0
44,bcfee016-b14f-4485-8e40-4dac24e076c6,STIM,2022-09-30,normal,2022-10-13,2022-10-11,bcfee016-b14f-4485-8e40-4dac24e076c6,n_4595,1370,7081.0,15381,224,152.40,72.937740,31.40,144,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2022-09-02,2022-09-30,2022-11-03,2022-11-03,1=STIM&12=TRG&14=RET,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,BCPA low stim 150M/100CC + ADJ with GH day 1 +...,ARTReason_6=on&ARTReason_6_Other=on,IVF: Freeze All - Autologous: IVF: BCPA Gonado...,144.0,39.0,32.0,39.0,-98.0,-98.0,NaN,NaN,NaN,NaN,2023-01-15,NaN,NaN,NaN,919b70ba-4984-431c-a6b4-4b08b4f73aa2,a166e5c1-cf00-43b1-bfa3-a278f433d945,Aneuploidy Screening for Advanced Age,NaN,2023-11-17 14:06:20.974412-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,34.0
46,fa317bdc-c8a2-4abc-bfac-712b6c1120d9,STIM,2023-07-06,normal,2023-07-18,2023-07-16,fa317bdc-c8a2-4abc-bfac-712b6c1120d9,n_11990,42452,42453.0,25616,246,167.64,49.441627,17.59,70,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-06-05,2023-07-06,2023-07-31,2023-07-31,1=STIM&11=TRG&13=RET,4,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"MLEA, No adj, PGT-A, Fresh sperm. IVF consents...",ARTReason_15=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,70.0,39.0,31.0,39.0,-98.0,-98.0,1.0,NaN,2023-06-05,NaN,2023-10-18,NaN,NaN,NaN,NaN,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,NaN,NaN,2024-10-31 09:58:11.824242-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,19097,19098,NaN,NaN,25.0
48,0d1a5dcc-7788-46a2-9ccc-fbc01c9f590b,STIM,2022-09-01,poor,NaT,NaT,0d1a5dcc-7788-46a2-9ccc-fbc01c9f590b,n_4264,30996,30997.0,12578,275,182.88,74.026363,22.13,60,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2022-09-01,2022-09-01,2023-10-12,2023-10-12,1=STIM,4,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Embryo freeze, PGT-A. RR consent IS 9/9/22\nLa...",ARTReason_7=on,IVF: Freeze All - Autologous: Random Stim Start,66.0,37.0,39.0,39.0,-98.0,-1.0,NaN,NaN,NaN,NaN,2023-01-14,NaN,NaN,NaN,c7a51ada-7edd-4d24-a502-3e5adee28253,a166e5c1-cf00-43b1-bfa3-a278f433d945,NaN,NaN,2023-11-17 14:06:20.28004-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,406.0
49,5ce5e173-e388-4773-b8d5-93b6d6c89da2,STIM,2023-09-07,normal,2023-09-22,2023-09-20,5ce5e173-e388-4773-b8d5-93b6d6c89da2,n_8487,23258,23298.0,28983,3972,167.64,56.758081,20.20,63,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-07-19,2023-09-07,2023-10-20,2023-10-20,1=STIM&14=TRG&16=RET,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"IVF MLEA +Dexamethasone, no other ADJ, Low sti...",ARTReason_15=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1497.0,38.0,37.0,38.0,0.0,-1.0,10.0,NaN,NaN,NaN,2023-10-05,NaN,NaN,NaN,ea9c624f-3e22-432b-852a-82ea25d64138,0aff226b-189d-4bc8-8fec-0c5e39f3dbeb,Elective PGT,PGT-A,2024-10-31 09:58:14.182377-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,6457732,33004417,NaN,Abnormal semen parameters,43.0
50,18411820-92ca-4232-9152-2eebcab56195,STIM,2023-06-10,normal,2023-06-24,2023-06-22,18411820-92ca-4232-9152-2eebcab56195,n_7335,41292,41293.0,24888,2943,165.10,77.564388,28.46,144,Completed,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2023-05-12,2023-06-10,2023-06-30,2023-06-30,1=STIM&13=TRG&15=RET,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Long Estrace SS+ CC with AJD no PGTA\n06-24-23...,ARTReason_6=on&ARTReason_6_DimOv=on,IVF: Freeze All - Autologous: Long Estrace Gon...,144.0,39.0,309.0,39.0,-98.0,-98.0,10.0,NaN,NaN,NaN,2023-09-24,NaN,NaN,NaN,18dfd17f-4692-4010-9039-138a1aa9486b,0f955604-a115-43e8-b33a-ed725e2e4c11,NaN,NaN,2024-10-30 11:32:44.130939-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,Laboratory routine,20.0

In [23]:
# displaying cases where retrieval_date is NA
merged_df[merged_df["retrieval_date"].isna() & (merged_df["status"] == "Completed")]

,cycleid,label,eventdate,response_type,retrieval_date,trigger_date,id,sart_id,patid,partnerid,barcode,chloe_id,height,weight,bmi,addedby,status,closed,cycletype,schedulestart,cyclestart,cycleend,scheduleend,event_labels,doctor,plan_treatment,main_note,art_reason,cycle_name,cyclecoordinator,icsi_tech,icsi_witness,insemination_tech,hist_smoker,hist_pat_surg_sterile,hist_monthsattempting,manual_culturestart,planned_start_date,planned_retrieval_date,orig_scheduleend,edd,calc_basedate,calc_type,last_prospective_report_id,last_final_report_id,pgt_reason,pgt_type,last_final_report_date,eggsource_eligibility,spermsource_eligibility,planned_eggsource,planned_spermsource,end_reason,icsi_reason,duration
33,9b807cfd-03f6-46ba-b745-8f8f703471ae,STIM,2022-04-18,poor,NaT,NaT,9b807cfd-03f6-46ba-b745-8f8f703471ae,n_7799,28194,28195.0,11040,178,157.48,67.585344,27.25,14,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2022-03-28,2022-04-18,2023-06-01,2023-06-01,1=STIM,9,4e625189-d13b-4ca1-9f4d-463506ae7a5f,KPRPMG2022-2\nMLEA standard stim w/ clomid w/ ...,ARTReason_1=on&ARTReason_1_AbnormSpermParams=o...,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,0.0,39.0,37.0,39.0,NaN,NaN,NaN,NaN,2022-03-28,NaN,2022-08-10,NaN,NaN,NaN,NaN,a166e5c1-cf00-43b1-bfa3-a278f433d945,"Aneuploidy Screening for Advanced Age, Electiv...",PGT-A,2023-11-17 14:06:16.5656-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,PATIENT,PARTNER,NaN,"PGT, Laboratory routine",409.0
34,87a248a8-c4a1-4842-bc54-efb91c02ef4a,STIM,2021-12-31,poor,NaT,NaT,87a248a8-c4a1-4842-bc54-efb91c02ef4a,n_2156,24828,24829.0,10445,180,160.02,55.882646,22.00,41,Completed,True,9a4aac0e-cf54-458a-87dc-506edb0e98ec,2021-12-22,2021-12-31,2022-01-14,2022-01-14,1=STIM,7,4e625189-d13b-4ca1-9f4d-463506ae7a5f,IVF LONG ESTRACE + ADJ + CC +PGT-A\nER: Reques...,ARTReason_13=on&ARTReason_13_Specify=DOR,IVF: Freeze All - Autologous: IVF: Long Estrac...,41.0,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,2021-11-22,2022-01-11,2022-05-06,NaN,NaN,NaN,NaN,NaN,Aneuploidy Screening for Advanced Age,PGT-A,NaN,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,patient,partner,NaN,Laboratory routine,14.0
37,fa3574ce-b1b2-440e-a60b-9c4f0c44e4c9,STIM,2023-06-16,poor,NaT,NaT,fa3574ce-b1b2-440e-a60b-9c4f0c44e4c9,n_11935,27047,27048.0,22876,188,167.64,67.313188,23.95,53,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-05-24,2023-06-16,2023-06-28,2023-06-28,1=STIM,5,02672e1f-371b-433a-be83-8664dfe7412d,"MLEA LOW (225M/50CC) + Adj, GH on SD1, EGG FRE...",ARTReason_7=on,Oocyte Freeze Cycle - Autologous: IVF: MLEA Go...,53.0,NaN,NaN,NaN,-98.0,-1.0,1.0,NaN,NaN,NaN,2023-10-06,NaN,NaN,NaN,NaN,5fa03fd6-3bb7-4417-aa35-fe6a8953865f,NaN,NaN,2024-10-30 12:55:46.630403-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,NaN,12.0
48,0d1a5dcc-7788-46a2-9ccc-fbc01c9f590b,STIM,2022-09-01,poor,NaT,NaT,0d1a5dcc-7788-46a2-9ccc-fbc01c9f590b,n_4264,30996,30997.0,12578,275,182.88,74.026363,22.13,60,Completed,True,ae7c0905-13b6-41a9-899e-fe7f883bf28f,2022-09-01,2022-09-01,2023-10-12,2023-10-12,1=STIM,4,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Embryo freeze, PGT-A. RR consent IS 9/9/22\nLa...",ARTReason_7=on,IVF: Freeze All - Autologous: Random Stim Start,66.0,37.0,39.0,39.0,-98.0,-1.0,NaN,NaN,NaN,NaN,2023-01-14,NaN,NaN,NaN,c7a51ada-7edd-4d24-a502-3e5adee28253,a166e5c1-cf00-43b1-bfa3-a278f433d945,NaN,NaN,2023-11-17 14:06:20.28004-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,NaN,406.0
84,0ddfe78d-cf15-4e24-975c-4d006dfb18ab,STIM,2022-11-17,poor,NaT,NaT,0ddfe78d-cf15-4e24-975c-4d006dfb18ab,n_5182,30468,30469.0,18618,477,162.56,67.948218,25.71,55,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2022-10-15,2022-11-17,2022-12-30,2022-12-30,1=STIM&-33=LMP,3,4e625189-d13b-4ca1-9f4d-463506ae7a5f,MLEA / STANDARD / 75M / 125F / NO ADJ / SPERM:...,ARTReason_15=on,IVF: Freeze All - Autologous: IVF: MLEA Gonado...,66.0,32.0,30.0,32.0,-98.0,-1.0,8.0,NaN,2022-11-17,NaN,2022-11-30,NaN,NaN,NaN,b2aa0a2a-5bac-4c69-9f08-ea0f53f6e56f,a166e5c1-cf00-43b1-bfa3-a278f433d945,Aneuploidy Screening for Advanced Age,NaN,2023-11-17 14:06:22.296812-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,7113,7114,NaN,NaN,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2545,b274fae1-d49f-46d1-aa57-455232aabde2,STIM,2025-03-28,poor,NaT,NaT,b274fae1-d49f-46d1-aa57-455232aabde2,n_13786,75709,75710.0,99828,45871,175.26,68.220374,22.21,1563,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2025-03-03,2025-03-28,2025-07-01,2025-07-01,NaN,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,DO NOT SHARE SEX OF EMBRYOS\nLab Plan: ICSI us...,NaN,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1563.0,39.0,31.0,39.0,-98.0,-98.0,12.0,NaN,2025-03-03,2025-04-09,2025-07-16,NaN,NaN,NaN,c8fb60ce-af94-4b90-9263-6c7fc7f5a236,89371958-ca1c-43b5-bd2a-0d25675e79b4,Aneuploidy Screening for Advanced Age,PGT-A,2026-04-07 16:09:00.501584-07,NaN,NaN,NaN,NaN,NaN,Laboratory routine,95.0
2603,d4a0da9b-94b4-4505-aef2-ca8c422d3400,STIM,2025-05-22,poor,NaT,NaT,d4a0da9b-94b4-4505-aef2-ca8c422d3400,n_14264,86764,NaN,104316,50359,182.88,75.296423,22.51,2025,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2025-04-23,2025-05-22,2025-10-30,2025-10-30,NaN,3,02672e1f-371b-433a-be83-8664dfe7412d,Lab Plan: Oocyte Vitrification for social fert...,ARTReason_7=on,Oocyte Freeze Cycle - Autologous: BCPA Gonadot...,2025.0,NaN,NaN,NaN,0.0,-1.0,0.0,NaN,2025-04-23,NaN,2025-09-11,NaN,NaN,NaN,8d990240-0fed-4f24-a5e6-6022f0c2ee1f,6eb07adb-4a08-4cca-ac94-281b3216a457,NaN,NaN,2025-06-02 10:31:29.854508-07,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,63409,NaN,NaN,NaN,161.0
2853,426be6db-3481-4b64-94f3-bfd1bce48606,STIM,2025-08-22,poor,NaT,NaT,426be6db-3481-4b64-94f3-bfd1bce48606,n_15100,87061,87062.0,122730,68773,170.18,76.112890,26.28,66,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2025-07-17,2025-08-22,2025-09-23,2025-09-23,NaN,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Lab Plan: ICSI using frozen donor sperm: #1353...,ARTReason_13=on&ARTReason_13_Specify=procreati...,IVF: Freeze All - Autologous: MLEA Gonadotropi...,66.0,37.0,35.0,37.0,0.0,-1.0,NaN,NaN,2025-08-22,NaN,2025-11-29,NaN,NaN,NaN,979187de-d34d-4c4a-abed-4db8f371a52c,e5106df5-e155-45a3-aaee-6d4a3f8d067f,Aneuploidy Screening for Advanced Age,NaN,2025-09-01 11:15:53.677261-07,Autologous/SIP Use Only Not Evaluated for Infe...,ELIGIBLE Donor,63706,NaN,NaN,NaN,32.0
3077,4747dd23-f9ab-4182-a5b8-82540efa2160,STIM,2025-11-21,poor,NaT,NaT,4747dd23-f9ab-4182-a5b8-82540efa2160,n_16254,92077,92078.0,122367,68410,167.64,72.579401,25.83,2025,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2025-10-16,2025-11-21,2025-12-23,2025-12-23,NaN,4,31874673-6e93-4ec2-b175-a8e2cc4860af,IVF converted to IUI / Sperm: Partner - Fresh ...,ARTReason_6=on&ARTReason_6_DimOv=on&ARTReason_...,IVF converted to IUI,2025.0,NaN,NaN,NaN,0.0,-1.0,24.0,NaN,2025-08-19,NaN,2026-02-28,2026-08-31,2025-11-24,retrieval,NaN,eb33ad7b-5ec9-406d-ad0b-8acbe14c81b8,NaN,NaN,2025-12-04 10:51:26.32299-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,68722,68723,NaN,NaN,32.0
3190,32d005b5-cafc-4d05-a7f3-2e1cfa6eab42,STIM,2026-01-02,poor,NaT,NaT,32d005b5-cafc-4d05-a7f3-2e1cfa6eab42,n_16569,88550,88551.0,141937,87980,160.02,75.477860,29.48,1563,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2025-12-17,2026-01-02,2026-02-10,2026-02-10,NaN,1,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Lab Plan: ICSI using frozen sperm: FS25-197 / ...,ARTReason_6=on&ARTReason_6_DimOv=on&ARTReason_...,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1563.0,32.0,30.0,32.0,-98.0,-98.0,8.0,NaN,2025-12-10,2026-01-14,2026-05-01,NaN,NaN,NaN,864e5a0e-1841-41c9-bf05-5fd1066e1056,7eccbf17-a729-44e8-b9a7-21976937fbe5,Elective PGT,PGT-A,2026-02-02 10:36:14.498869-08,NaN,NaN,NaN,NaN,NaN,Laboratory routine,39.0

In [25]:
#save to csv
merged_df.to_csv("../data/emr_file_merging_output.csv", index=False)

In [17]:
# cycleid "c72fe00b-5da9-440c-b6e2-0a9c3f89afde" retreival date is 2022-06-01

import pandas as pd

# 1. Run each processing script to build its cleaned dataframe.
#    Assumes: the notebook sits at the repo root, and each script
#    leaves its final result in a variable called `df`.
%run scripts/emr_cycle_event_processing.py
response_df = df.copy()    # event-level data carrying response_type

%run scripts/emr_cycle_processing.py
cycle_df = df.copy()       # cleaned emr_cycle (one row per cycle)

# 2. Merge: response_df.cycleid  ->  cycle_df.id
LEFT_KEY  = "cycleid"      # join key in response_df  (confirm exact name)
RIGHT_KEY = "id"           # join key in cycle_df

# keys must be the SAME type or nothing matches — emr_cycle.id is text
response_df[LEFT_KEY] = response_df[LEFT_KEY].astype(str).str.strip()
cycle_df[RIGHT_KEY]   = cycle_df[RIGHT_KEY].astype(str).str.strip()

merged = response_df.merge(
    cycle_df,
    left_on=LEFT_KEY,
    right_on=RIGHT_KEY,
    how="left",                      # keep every response row
    suffixes=("_event", "_cycle"),   # disambiguate any clashing column names
)

# 3. Sanity check
print(f"response rows : {len(response_df):,}")
print(f"merged rows   : {len(merged):,}")
print(f"unmatched     : {merged[RIGHT_KEY].isna().sum():,}")  # response rows with no cycle match
merged.head()