In [ ]:
# calling in data from: 1)emr cycle merged data, 2) emr aspirations data, and 3) lab ivf data

# Setup

In [27]:
from pathlib import Path
import pandas as pd

In [28]:
#setting display options to show all columns and full width
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)        # Allow full width

## Merging dfs

Calling in data from: 1)emr cycle merged data, 2) emr aspirations data, and 3) lab ivf data

In [83]:
# --- emr_cycle_merged import ---
cycle_merged_PATH = Path("../data/emr_file_merging_output.csv")

# loading data
cycle_merged_df = pd.read_csv(cycle_merged_PATH)

# in cycle_merged_df, get rid of duplications of full rows, keeping only the first occurrence
cycle_merged_df = cycle_merged_df.drop_duplicates(keep='first')

# --- emr_aspirationst ---
aspirations_PATH = Path("../data/emr_cycle_aspirations_filtered.csv")

# loading data
aspirations_df = pd.read_csv(aspirations_PATH)

# in aspirations_df, get rid of duplications of full rows, keeping only the first occurrence
aspirations_df = aspirations_df.drop_duplicates(keep='first')

# --- lab_ivf import ---
lab_ivf_PATH = Path("../data/ivf_lab_data_cleaned.csv")

# loading data
lab_ivf_df = pd.read_csv(lab_ivf_PATH)

# in lab_ivf_df, get rid of duplications of full rows, keeping only the first occurrence
lab_ivf_df = lab_ivf_df.drop_duplicates(keep='first')

In [109]:
display(lab_ivf_df.head())

,Cycle #,Patient Name,Procedure,ER Date,Age,Donor Eggs,FDA,AMH Level,Primary Dr.,STIM D3 E2,Peak E2,Dose Increased,Menopur dosage,Follistim dosage,Clomiphene dosage,Ganirellx,Indomethacin,Lupon & Pregnyl Trigger,Endo Thickness,P4 Level,# of Follicles,# Egg retrieved/Thawed,Double Lumen,ER Dr.,ER Tech,Hyase Tech,TESA/TESE,Zymot,SW Tech,Egg FRZ,ICSI hours post ER,ICSI Tech,# Mature eggs,CC,# 2PN,# Lysed,# 0PN,# 1PN,# 3PN,# of Bx,D5 Normal G,D5 Normal F,D5 Normal P,D5 Abnormal G,D5 Abnormal F,D5 Abnormal P,D6 Normal G,D6 Normal F,D6 Normal P,D6 Abnormal G,D6 Abnormal F,D6 Abnormal P,D7 Normal G,D7 Normal F,D7 Normal P,D7 Abnormal G,D7 Abnormal F,D7 Abnormal P,# Complex ABN,# Mosaic,Chaotic,# no signal,#0PN to blast,# 0PN to Eploid blast,# 1PN to Euploid blast,# of D5 usable blast,# of D6 usable blast,# of D7 usable blast,PGT,EGG FRZ Tech,D5 Bx Tech,D5 FRZ Tech,D6 Bx Tech,D6 FRZ Tech,D7 Bx Tech,D7 FRZ Tech,Reasons for No ET,Comments,clinic
0,#24-003,"Sridhar, Priya",IVF Cycle,1/4/2024,39.0,N,NaN,0.441,STAN,48,2016.0,Y,3825.0,3925.0,1100,NaN,NaN,NaN,3.4,0.33,7.0,7.0,Y,FLO,KON,TIN,N,N,KUC,N,3.5,ZHA,4.0,N,1.0,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,Y,NaN,NaN,NaN,ZHA,KIM,NaN,NaN,No normal blast,NaN,RPSD
1,#24-008,"Morton, Nissa",IVF Cycle,1/8/2024,41.0,N,NaN,1.61,AGA,142,4070.0,N,1350.0,2025.0,1000,NaN,NaN,NaN,8.7,6.48,21.0,28.0,N,SU,KON,KON,N,Y,KON,N,5,ZHA,13.0,N,6.0,NaN,6.0,NaN,1.0,6.0,1.0,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN,Y,NaN,ZHA,ARA,ZHA,ARA,NaN,NaN,Embryo banking,NaN,RPSD
2,#24-012,"Curtis, Megan",IVF Cycle,1/8/2024,35.0,N,NaN,2.02,SU,244,5775.0,N,1350.0,1350.0,NaN,Y,NaN,NaN,7.2,10.28,9.0,22.0,N,DUL,KON,KIM,N,Y,ARA,N,4.5,KIM,19.0,Y,14.0,NaN,2.0,3.0,NaN,10.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,5.0,5.0,NaN,Y,NaN,ZHA,ARA,KIM,ARA,NaN,NaN,Embryo banking,NaN,RPSD
3,#24-013,"Limon, Noerena",IVF Cycle,1/9/2024,41.0,N,NaN,4.24,AGA,69,5942.0,N,825.0,1025.0,800,NaN,NaN,NaN,10.2,10.78,11.0,37.0,N,DUL,KON,ARA,N,Y,CRU,N,5,ZHA,27.0,N,18.0,7.0,2.0,NaN,NaN,4.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,Y,NaN,ZHA,ARA,KIM,ARA,NaN,NaN,No normal blast,NaN,RPSD
4,#24-014,"Cesare, Catherine",IVF Cycle,1/9/2024,32.0,N,NaN,1.88,GAR,71,1445.0,Y,2400.0,2400.0,1100,Y,NaN,NaN,7.4,NaN,6.0,20.0,N,GAR,KON,KIM,N,Y,CRU,N,4,ZHA,14.0,N,11.0,1.0,2.0,NaN,NaN,10.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,1.0,Y,NaN,ZHA,ARA,KIM,ARA,KIM,TIN,Embryo banking,NaN,RPSD

In [85]:
# in aspirations_df, find and display non-NA duplicates of accession_number
duplicates = aspirations_df[aspirations_df['accession_number'].notnull() & aspirations_df.duplicated(subset='accession_number', keep=False)]
display(duplicates)
duplicates.shape

,cycleid,patid,donorid,retrieved,retrievedby,oocytes_retrieved,complication,note,denuding_performed,denuding_performedby,retrievedtech,labassistant,scrub_tech,crna,needle_type,duration,accession_number
86,0c65c03a-461b-445e-ada8-6e5bf08f7cbb,24465,NaN,2022-01-22 09:12:00,89.0,3.0,NaN,NaN,2022-01-22 12:30:00-08,37.0,37.0,36.0,282.0,Leann Johnson,Double lumen needle,30,22-031
105,dc7e94b1-772d-4f04-af55-60741fef1359,24086,NaN,2022-01-10 09:11:00,3.0,17.0,NaN,NaN,2022-01-10 13:20:00-08,31.0,31.0,35.0,282.0,Leann Johnson,Cook Echotip 16 G,15,22-002
184,65b42a7e-a0b3-4106-a40e-56315c0605ad,26679,NaN,2022-03-01 08:29:00,94.0,11.0,NaN,NaN,2022-03-01 12:45:00-08,37.0,287.0,35.0,282.0,Leann Johnson,Double lumen needle,30,K22-033
248,fee4eac5-8ed2-45b3-b27e-8173fcece29a,26679,NaN,2022-03-01 08:29:00,94.0,11.0,NaN,NaN,2022-03-01 12:50:00-08,287.0,287.0,35.0,282.0,L. Johnson,Double lumen needle,34,K22-033
430,45fda419-ba4d-4b95-85e7-8838a9617afc,27166,NaN,2023-01-18 10:44:00,89.0,10.0,NaN,"KK clean alone, AY verified",2023-01-18 14:00:00-08,35.0,287.0,309.0,210.0,Leann Johnson,Double lumen needle,25,22-031
499,4304623f-e3e5-412b-a519-5d3c26a90a6e,28651,NaN,2022-09-09 08:36:00,91.0,19.0,NaN,"Patient Identified by Katie Nguyen, Dishes ver...",2022-09-09 10:45:00-07,37.0,35.0,309.0,43.0,Leann Johnson,Cook Echotip 16 G,30,22-622
501,1fac96bc-63fc-448c-8747-4966b6b9f252,32941,NaN,2022-09-12 08:41:00,93.0,22.0,NaN,Retrieved by: Renee Rivas,2022-09-12 13:10:00-07,38.0,35.0,309.0,705.0,Leann Johnson,Cook Echotip 16 G,30,22-622
612,dd9e893c-4690-425f-82b2-bf51e0146fe1,35847,NaN,2022-11-15 08:38:00,286.0,7.0,NaN,Scrub Tech: Ashley training,2022-11-15 12:50:00-08,37.0,35.0,309.0,771.0,Leann Johnson,Double lumen needle,25,K22-204
614,0ed7131f-4fe3-48a7-b220-d8b16e8167dd,35350,NaN,2022-11-17 07:12:00,286.0,11.0,NaN,NaN,2022-11-17 11:40:00-08,38.0,35.0,309.0,210.0,Leann Johnson,Double lumen needle,50,K22-204
662,199c64b3-1fb8-4814-bb92-4da366583b2e,23451,NaN,2023-01-05 09:08:00,90.0,5.0,NaN,Retrieved by: Dr. Medica second side,2023-01-05 12:30:00-08,37.0,35.0,32.0,210.0,Leann Johnson,Double lumen needle,30,22-002
672,dc15f2fc-abba-4321-afdb-fe4bd873168c,37103,NaN,2023-01-10 11:18:00,89.0,14.0,NaN,NaN,2023-01-10 14:05:00-08,287.0,32.0,309.0,285.0,Leann Johnson,Cook Echotip 16 G,11,23-012
779,a139c402-0c17-438e-b86a-130059a22a97,29086,NaN,2023-03-14 10:57:00,90.0,15.0,NaN,"Retrieved by:Dr. Dayo left side, Scrub Tech: M...",2023-03-14 14:03:00-07,35.0,35.0,309.0,NaN,Leann Johnson,Cook Echotip 16 G,20,23-176
1006,dd7ed668-d636-4767-9be1-0bc9adf85227,32743,NaN,2023-07-01 08:06:00,91.0,7.0,NaN,Pt ID by Madison Bishop,2023-07-01 10:03:00-07,31.0,287.0,31.0,285.0,Leann Johnson,Double lumen needle,30,23-489
1017,40fc2708-00cf-4cba-99d7-603068b2852f,39116,NaN,2023-07-04 09:02:00,89.0,20.0,NaN,NaN,2023-07-04 12:10:00-07,287.0,31.0,35.0,285.0,Leann Johnson,Cook Echotip 16 G,10,23-489
1127,dc8d58f2-2195-4101-87cd-3c0b6a48233c,28688,NaN,2023-08-21 08:08:00,91.0,10.0,NaN,NaN,2023-08-21 12:10:00-07,38.0,287.0,309.0,1366.0,Leann Johnson,Double lumen needle,38,23-620
1129,3a812747-d526-4000-8e79-3dae3193e594,41125,NaN,2023-08-21 09:43:00,903.0,24.0,NaN,NaN,2023-08-21 12:50:00-07,287.0,287.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,16,23-620
1192,68552120-cc80-4a2e-bfc8-b37d56e6bbb2,41224,NaN,2023-10-11 07:43:00,94.0,9.0,NaN,NaN,2023-10-11 09:37:00-07,31.0,35.0,309.0,1431.0,Leann Johnson,Double lumen needle,20,k23-226
1311,9ff94316-851a-4d74-919e-419268af3841,49705,NaN,2023-11-22 08:08:00,286.0,27.0,NaN,NaN,2023-11-22 10:18:00-08,32.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,20,k23-226
1337,78829591-54f9-4684-ab6f-ed68d4936801,41488,NaN,2024-01-09 11:01:00,3.0,20.0,NaN,Dishes verified by a 2nd Embryologist: Reviewe...,2024-01-09 14:33:00-08,287.0,35.0,309.0,285.0,Leann Johnson,Cook Echotip 16 G,11,24-014
1338,47f82182-5f32-4a80-8023-d1a416c580fb,43237,NaN,2024-01-09 07:35:00,90.0,22.0,NaN,Retrieved by: Dr. Dayo left side,2024-01-09 11:35:00-08,287.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,11,23-012
1347,a8a40563-8103-4036-9142-9ad039662cc5,43249,NaN,2024-01-28 08:32:00,91.0,20.0,NaN,NaN,2024-01-28 10:40:00-08,37.0,35.0,35.0,1366.0,Leann Johnson,Cook Echotip 16 G,15,24-
1379,eaea695c-5e6b-4a31-97da-e542cf2ed52c,52114,NaN,2024-01-17 07:16:00,286.0,20.0,NaN,Retrieved by: Dr. Rivas right side,2024-01-17 09:15:00-08,32.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,20,k24-008
1443,64d90e33-299e-40ee-aeb6-1d15c8113819,30235,NaN,2024-02-28 11:45:00,92.0,8.0,NaN,NaN,2024-02-28 13:36:00-08,31.0,287.0,309.0,1366.0,L. Johnson,Double lumen needle,60,23-176
1456,a19f9724-22d4-4225-ae1d-cd3f58ffe2cb,49012,NaN,2024-03-05 12:13:00,89.0,9.0,NaN,Dishes verified by a 2nd Embryologist: AY/GK,2024-03-05 00:00:00-08,31.0,35.0,38.0,43.0,L. Johnson,Double lumen needle,17,24-200
1520,40f42f74-64c1-41b5-8405-036e15bdba90,51138,NaN,2024-03-28 12:35:00,90.0,9.0,NaN,NaN,2024-03-28 15:35:00-07,31.0,31.0,31.0,63.0,L. Johnson,Double lumen needle,20,24-296
1558,fbec21ec-82ea-4c62-9455-f735d5829940,51058,NaN,2024-04-02 09:05:00,90.0,7.0,NaN,NaN,2024-04-02 12:40:00-07,39.0,35.0,309.0,1366.0,Leann Johnson,Double lumen needle,25,24-296
1568,5e1da50c-d5cd-4fb9-af86-912f191bdbc8,7197,NaN,2024-04-18 15:24:00,3.0,11.0,NaN,NaN,2024-04-18 00:00:00-07,31.0,37.0,31.0,52.0,"Johnson, Leann",Double lumen needle,26,24-
1587,3d5108dd-6658-4256-a1c8-06d734aa9d67,45880,NaN,2024-05-02 00:00:00,3.0,2.0,NaN,NaN,2024-05-02 15:05:00-07,31.0,31.0,287.0,1695.0,Leann Johnson,Double lumen needle,NaN,24-
1641,fc427a89-0cff-41c2-9f9e-e3f9b61d765e,47329,NaN,2024-06-11 08:57:00,90.0,15.0,NaN,GK second half w KK/AY,2024-06-11 12:29:00-07,287.0,35.0,309.0,285.0,Leann Johnson,Cook Echotip 16 G,10,24-453
1658,0bba3ca0-d924-4063-9c30-ae214a8e6fc1,44429,NaN,2024-05-29 15:19:00,92.0,42.0,NaN,NaN,2024-05-29 18:15:00-07,37.0,32.0,309.0,43.0,Leann Johnson,Cook Echotip 16 G,19,24-453
1688,aa2cc9a7-c3b8-4f48-aaa7-fea012bc0634,58657,NaN,2024-06-23 12:45:00,92.0,16.0,NaN,NaN,2024-06-23 14:40:00-07,37.0,287.0,309.0,63.0,Colleen,Cook Echotip 16 G,20,24-575
1755,fdef721f-6689-4265-8942-656233a7b088,52477,NaN,2024-07-16 09:05:00,90.0,11.0,NaN,NaN,2024-07-16 12:20:00-07,37.0,35.0,31.0,1366.0,Leann Johnson,Double lumen needle,20,24-575
1803,c3fa72bb-91af-4f90-b866-28a9b5e0ba75,55909,NaN,2024-08-26 08:39:00,89.0,14.0,NaN,Egg cleaning AY/GK,2024-08-26 11:56:00-07,38.0,31.0,2487.0,1366.0,Sam Polikowski,Double lumen needle,20,24-694
1806,8860b170-26a4-4aa6-8487-df1e6c4f6368,45950,NaN,2024-08-25 08:44:00,92.0,7.0,NaN,NaN,2024-08-25 10:30:00-07,35.0,35.0,35.0,63.0,April King,Double lumen needle,10,24-694
1945,0d94c44c-51e1-4e4a-b9e3-7518dc0a2698,62377,NaN,2024-11-10 09:13:00,89.0,5.0,NaN,Retrieved by Dr. Dayo,2024-11-10 13:15:00-08,39.0,37.0,309.0,285.0,Leann Johnson,Cook Echotip 16 G,16,24-881
1972,ce85fc95-1a84-44f7-ba0c-95dd40c18d72,68845,NaN,2024-11-20 14:05:00,89.0,8.0,NaN,verified by AY,2024-11-20 16:30:00-08,37.0,309.0,2487.0,1431.0,Leann Johnson,"Cook Echotip 16 G, Double lumen needle",17,24-927
1978,e19f5fd5-9369-47fc-8407-bd47cb48b04f,73267,NaN,2024-11-20 15:35:00,3.0,34.0,NaN,verified by ay,2024-11-20 17:45:00-08,39.0,309.0,30.0,1366.0,Leann Johnson,Cook Echotip 16 G,23,24-927
2048,c36a84c5-c236-4f89-91f2-c4fcba3dae65,72673,NaN,2025-01-08 11:22:00,3.0,7.0,NaN,NaN,2025-01-08 14:10:00-08,37.0,35.0,2487.0,1431.0,Leann Johnson,Double lumen needle,30,24-014
2063,01b6c75f-50fc-49e8-9824-05c4d9e3ebbc,53005,NaN,2025-02-04 10:07:00,89.0,9.0,NaN,NaN,2025-02-04 14:30:00-08,32.0,309.0,2487.0,1366.0,L. Johnson,Double lumen needle,22,25-090
2065,17ab2b47-a7f8-4874-9715-c1e388bd43ea,58120,NaN,2025-02-05 07:59:00,3.0,7.0,NaN,NaN,2025-02-05 13:50:00-08,32.0,309.0,2487.0,1366.0,L. Johnson,Double lumen needle,21,25-090
2075,be385adb-50ad-4fe6-93bf-50086d867b00,24380,NaN,2025-01-13 09:08:00,286.0,11.0,NaN,NaN,2025-01-13 13:10:00-08,38.0,35.0,2487.0,1695.0,Leann Johnson,Double lumen needle,50,k24-008
2112,b58db03e-09a6-4f42-b552-394b0e826080,88282,NaN,2025-02-11 07:35:00,286.0,18.0,NaN,GK/AY CLEANING,2025-02-11 11:55:00-08,39.0,309.0,2487.0,1366.0,L. Johnson,Cook Echotip 16 G,22,K25-039
2139,8da2ade8-ed57-4af8-8d75-ada5efafbfcc,79669,NaN,2025-02-24 07:32:00,94.0,13.0,NaN,NaN,2025-02-24 12:03:00-08,32.0,31.0,2487.0,1366.0,Leann,Cook Echotip 16 G,25,K25-039
2179,2f4a1535-2296-4eb8-b169-9fa3aef40071,66700,NaN,2025-03-13 09:10:00,89.0,8.0,NaN,NaN,2025-03-13 12:25:00-07,37.0,32.0,2487.0,285.0,Leann Johnson,Double lumen needle,30,24-200
2207,b45aeb12-a83f-431d-911f-a5318ddc79aa,87688,NaN,2025-03-25 09:07:00,90.0,24.0,NaN,DR DAYO\nGK/AY CLEANING,2025-03-25 13:55:00-07,38.0,309.0,3279.0,1366.0,L. Johnson,Cook Echotip 16 G,16,25-236
2208,f98ebabe-06f6-4ea4-a462-711e2231bafc,24531,NaN,2025-03-25 07:34:00,3.0,9.0,NaN,NaN,2025-03-25 12:20:00-07,39.0,309.0,3279.0,1366.0,L. Johnson,"Cook Echotip 16 G, Double lumen needle",46,25-236
2252,5ca3c3f7-a0d9-4279-b629-ef095261bf98,23131,NaN,2025-04-16 07:30:00,93.0,14.0,NaN,double checked by rt,2025-04-17 11:45:00-07,31.0,309.0,3279.0,1366.0,Megan,Double lumen needle,55,K25-082
2643,8f44c4fb-5532-42a8-ab50-39bcb2340c09,115045,NaN,2025-10-09 12:44:00,3213.0,14.0,NaN,NaN,2025-10-09 15:30:00-07,35.0,37.0,3279.0,63.0,Leann,Cook Echotip 16 G,7,24-881
2737,1e5098c1-dad4-47ab-ae99-d78325295629,119467,NaN,2025-11-26 10:04:00,93.0,9.0,NaN,NaN,2025-11-26 14:28:00-08,31.0,35.0,30.0,1200.0,Leann Johnson,Double lumen needle,60,K25-082
2766,d12f9266-760d-42fb-8878-651f2840576b,107622,NaN,2025-12-09 07:35:00,95.0,5.0,NaN,Patient Identified by Katlyn & Ashley B.\nEuni...,NaN,NaN,35.0,3279.0,1366.0,Leann Johnson,Double lumen needle,45,25-1074
2767,f53aa053-667f-478c-aa28-45dba4abd84a,123130,NaN,2025-12-09 09:10:00,90.0,16.0,NaN,NaN,2025-12-09 01:15:00-08,38.0,35.0,3279.0,52.0,LEANN JOHNSON,Cook Echotip 16 G,20,25-1074
2867,26463561-20bb-47ee-bc21-ec332b7ba21c,128509,NaN,2026-02-26 07:43:00,286.0,10.0,NaN,NaN,2026-02-26 09:45:00-08,31.0,35.0,4005.0,63.0,Leann Johnson,Double lumen needle,20,K26-067
2875,0746071a-4a23-49db-9a0f-2ee360c2b588,107556,NaN,2026-02-28 08:43:00,286.0,11.0,NaN,NaN,2026-02-28 12:30:00-08,39.0,31.0,2487.0,804.0,Leann,Cook Echotip 16 G,10,K26-067
3002,f32098b7-0a9e-445f-89d1-b85abf1aa4ae,126166,NaN,2026-04-01 14:00:00,93.0,27.0,NaN,NaN,2026-04-01 18:20:00-07,2487.0,38.0,4005.0,43.0,Leann Johnson,Cook Echotip 16 G,16,K26-113
3003,f25e9b2c-d074-4d86-8545-a85dc76674d3,139333,NaN,2026-04-02 07:36:00,93.0,8.0,NaN,NaN,2026-04-02 09:50:00-07,32.0,32.0,4005.0,285.0,Leann Johnson,Double lumen needle,22,K26-113

(55, 17)

In [71]:
# take the leading "#" out of lab_ivf_df's "Cycle #" column
lab_ivf_df['Cycle #'] = lab_ivf_df['Cycle #'].str.lstrip('#')

# now merging lab_ivf_df by "Cycle #" with aspirations_df by "accession_number", only keeping rows that are present in both dataframes
merged_df = pd.merge(lab_ivf_df, aspirations_df, left_on='Cycle #', right_on='accession_number', how='inner')

## drop accession_number column from merged_df
#merged_df.drop(columns=['accession_number'], inplace=True)

In [72]:
# now merging merged_df by "cycleid" with cycle_merged_df by "cycleid", only keeping rows that are present in both dataframes
merged_df = pd.merge(merged_df, cycle_merged_df, left_on='cycleid', right_on='cycleid', how='inner')

In [73]:
display(merged_df.head())
merged_df.shape

,Cycle #,Patient Name,Procedure,ER Date,Age,Donor Eggs,FDA,AMH Level,Primary Dr.,STIM D3 E2,Peak E2,Dose Increased,Menopur dosage,Follistim dosage,Clomiphene dosage,Ganirellx,Indomethacin,Lupon & Pregnyl Trigger,Endo Thickness,P4 Level,# of Follicles,# Egg retrieved/Thawed,Double Lumen,ER Dr.,ER Tech,Hyase Tech,TESA/TESE,Zymot,SW Tech,Egg FRZ,ICSI hours post ER,ICSI Tech,# Mature eggs,CC,# 2PN,# Lysed,# 0PN,# 1PN,# 3PN,# of Bx,D5 Normal G,D5 Normal F,D5 Normal P,D5 Abnormal G,D5 Abnormal F,D5 Abnormal P,D6 Normal G,D6 Normal F,D6 Normal P,D6 Abnormal G,D6 Abnormal F,D6 Abnormal P,D7 Normal G,D7 Normal F,D7 Normal P,D7 Abnormal G,D7 Abnormal F,D7 Abnormal P,# Complex ABN,# Mosaic,Chaotic,# no signal,#0PN to blast,# 0PN to Eploid blast,# 1PN to Euploid blast,# of D5 usable blast,# of D6 usable blast,# of D7 usable blast,PGT,EGG FRZ Tech,D5 Bx Tech,D5 FRZ Tech,D6 Bx Tech,D6 FRZ Tech,D7 Bx Tech,D7 FRZ Tech,Reasons for No ET,Comments,clinic,cycleid,patid_x,donorid,retrieved,retrievedby,oocytes_retrieved,complication,note,denuding_performed,denuding_performedby,retrievedtech,labassistant,scrub_tech,crna,needle_type,duration_x,accession_number,label,eventdate,response_type,retrieval_date,trigger_date,id,sart_id,patid_y,partnerid,barcode,chloe_id,height,weight,bmi,addedby,status,closed,cycletype,schedulestart,cyclestart,cycleend,scheduleend,event_labels,doctor,plan_treatment,main_note,art_reason,cycle_name,cyclecoordinator,icsi_tech,icsi_witness,insemination_tech,hist_smoker,hist_pat_surg_sterile,hist_monthsattempting,manual_culturestart,planned_start_date,planned_retrieval_date,orig_scheduleend,edd,calc_basedate,calc_type,last_prospective_report_id,last_final_report_id,pgt_reason,pgt_type,last_final_report_date,eggsource_eligibility,spermsource_eligibility,planned_eggsource,planned_spermsource,end_reason,icsi_reason,duration_y
0,24-008,"Morton, Nissa",IVF Cycle,1/8/2024,41.0,N,NaN,1.61,AGA,142,4070.0,N,1350.0,2025.0,1000,NaN,NaN,NaN,8.7,6.48,21.0,28.0,N,SU,KON,KON,N,Y,KON,N,5,ZHA,13.0,N,6.0,NaN,6.0,NaN,1.0,6.0,1.0,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN,Y,NaN,ZHA,ARA,ZHA,ARA,NaN,NaN,Embryo banking,NaN,RPSD,6a6cf5b9-3e88-4beb-b826-10233c17ef58,13737,NaN,2024-01-08 08:00:00,91.0,28.0,NaN,NaN,2024-01-08 12:19:00-08,35.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,8,24-008,STIM,2023-12-28,normal,2024-01-08,2024-01-06,6a6cf5b9-3e88-4beb-b826-10233c17ef58,n_9352,13737,9028.0,36734,3678,165.10,75.750016,27.79,66,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-11-13,2023-12-28,2024-01-24,2024-01-24,NaN,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Lab Plan: ICSI with ZyMot (if possible) - has ...,ARTReason_15=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,66.0,39.0,30.0,39.0,0.0,-1.0,12.0,NaN,2023-12-28,NaN,2024-03-27,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Aneuploidy Screening for Advanced Age,NaN,2024-10-31 13:28:36.863117-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,33001499,NaN,Laboratory routine,27.0
1,24-013,"Limon, Noerena",IVF Cycle,1/9/2024,41.0,N,NaN,4.24,AGA,69,5942.0,N,825.0,1025.0,800,NaN,NaN,NaN,10.2,10.78,11.0,37.0,N,DUL,KON,ARA,N,Y,CRU,N,5,ZHA,27.0,N,18.0,7.0,2.0,NaN,NaN,4.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,Y,NaN,ZHA,ARA,KIM,ARA,NaN,NaN,No normal blast,NaN,RPSD,a18856fe-981b-4d75-8b64-c737c3e5b929,29872,NaN,2024-01-09 09:15:00,90.0,37.0,NaN,NaN,2024-01-09 13:30:00-08,32.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,10,24-013,STIM,2023-12-27,normal,2024-01-09,2024-01-07,a18856fe-981b-4d75-8b64-c737c3e5b929,n_9344,29872,29873.0,36732,3425,165.10,67.272364,24.68,44,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-11-26,2023-12-27,2024-01-15,2024-01-15,NaN,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI with ZyMot, CC, AH, PGT-A, and ...",ARTReason_8=on,IVF: Freeze All - Autologous: BCPA Gonadotropi...,44.0,39.0,287.0,39.0,0.0,-1.0,0.0,NaN,2023-11-26,NaN,2024-01-13,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Aneuploidy Screening for Advanced Age,PGT-A,2024-10-31 13:28:36.765991-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,6517,6518,NaN,Laboratory routine,19.0
2,24-014,"Cesare, Catherine",IVF Cycle,1/9/2024,32.0,N,NaN,1.88,GAR,71,1445.0,Y,2400.0,2400.0,1100,Y,NaN,NaN,7.4,NaN,6.0,20.0,N,GAR,KON,KIM,N,Y,CRU,N,4,ZHA,14.0,N,11.0,1.0,2.0,NaN,NaN,10.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,1.0,Y,NaN,ZHA,ARA,KIM,ARA,KIM,TIN,Embryo banking,NaN,RPSD,78829591-54f9-4684-ab6f-ed68d4936801,41488,NaN,2024-01-09 11:01:00,3.0,20.0,NaN,Dishes verified by a 2nd Embryologist: Reviewe...,2024-01-09 14:33:00-08,287.0,35.0,309.0,285.0,Leann Johnson,Cook Echotip 16 G,11,24-014,STIM,2023-12-28,normal,2024-01-09,2024-01-07,78829591-54f9-4684-ab6f-ed68d4936801,n_9348,41488,41489.0,36774,3605,172.72,86.545527,29.01,66,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-11-11,2023-12-28,2024-01-23,2024-01-23,NaN,1,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI with ZyMot, CC, AH, PGT-A/M, an...",ARTReason_13=on&ARTReason_13_PGT=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,66.0,39.0,287.0,39.0,0.0,-1.0,13.0,NaN,2023-12-28,NaN,2024-03-25,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Either genetic parent is a known carrier of a ...,NaN,2024-10-31 13:28:36.811054-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,18133,18134,NaN,"Abnormal semen parameters, Laboratory routine",26.0
3,24-014,"Cesare, Catherine",IVF Cycle,1/9/2024,32.0,N,NaN,1.88,GAR,71,1445.0,Y,2400.0,2400.0,1100,Y,NaN,NaN,7.4,NaN,6.0,20.0,N,GAR,KON,KIM,N,Y,CRU,N,4,ZHA,14.0,N,11.0,1.0,2.0,NaN,NaN,10.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,1.0,Y,NaN,ZHA,ARA,KIM,ARA,KIM,TIN,Embryo banking,NaN,RPSD,c36a84c5-c236-4f89-91f2-c4fcba3dae65,72673,NaN,2025-01-08 11:22:00,3.0,7.0,NaN,NaN,2025-01-08 14:10:00-08,37.0,35.0,2487.0,1431.0,Leann Johnson,Double lumen needle,30,24-014,STIM,2024-12-26,normal,2025-01-08,2025-01-06,c36a84c5-c236-4f89-91f2-c4fcba3dae65,n_12973,72673,72674.0,87948,33991,160.02,55.519772,21.68,1497,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2024-11-09,2024-12-26,2025-01-30,2025-01-30,NaN,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI, CC, AH, PGT-A with Igenomix, a...",ARTReason_7=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1497.0,37.0,39.0,37.0,-98.0,-98.0,0.0,NaN,NaN,NaN,2025-03-24,NaN,NaN,NaN,7ab22d8d-08ce-43b3-9297-85f62e8028ea,091cafe9-ea4b-4778-aff4-f71296d3d2af,Aneuploidy Screening for Advanced Age,NaN,2025-11-12 17:35:31.454311-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,49318,49319,NaN,Laboratory routine,35.0
4,24-016,"Aspis, Victoria",IVF Cycle,1/11/2024,36.0,N,NaN,2.76,STAN,102,1790.0,N,825.0,1550.0,600,NaN,Y,Y,9.7,9.55,15.0,17.0,N,STAN,ARA,KIM,N,N,CRU,N,4.5,KIM,16.0,Y,11.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,6.0,NaN,Y,NaN,ZHA,TIN,ZHA,TIN,NaN,NaN,Embryo banking,NaN,RPSD,8da1aec1-69f6-4241-9a16-e665499f50be,46141,NaN,2024-01-11 07:40:00,89.0,17.0,NaN,NaN,2024-01-11 11:40:00-08,287.0,32.0,31.0,1366.0,Leann Johnson,Cook Echotip 16 G,12,24-016,STIM,2023-12-29,normal,2024-01-11,2024-01-09,8da1aec1-69f6-4241-9a16-e665499f50be,n_9375,46141,46142.0,37326,3474,149.86,51.255999,22.82,1563,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-11-14,2023-12-29,2024-01-24,2024-01-24,NaN,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI, CC, AH, PGT-A with Igenomix, a...",NaN,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1563.0,287.0,31.0,287.0,-98.0,-98.0,1.0,NaN,2023-11-14,2024-01-10,2024-03-28,NaN,NaN,NaN,NaN,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Aneuploidy Screening for Recurrent Miscarriage,PGT-A,2024-10-31 13:28:36.900047-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,Laboratory routine,26.0

(362, 150)

In [ ]:
"""
# write to csv so that I can just take a peak at the data in excel
merged_df.to_csv("../data/test_merged_data.csv", index=False)
"""

PermissionError: [Errno 13] Permission denied: '../data/test_merged_data.csv'

## Adjusting data to look at proportions of usable embryos

In [104]:
df = merged_df.copy()

In [105]:
# strip all column names of leading and trailing whitespace
df.columns = df.columns.str.strip()

In [106]:
# fill in missing values for "# of D5 usable blast", "# of D6 usable blast", and "# of D7 usable blast" with 0, then create a new column "usable_embryos" that sums these three columns
df["usable_embryos"] = (
    df["# of D5 usable blast"].fillna(0)
    + df["# of D6 usable blast"].fillna(0)
    + df["# of D7 usable blast"].fillna(0)
    + df["D5 Normal G"].fillna(0)
    + df["D5 Normal F"].fillna(0)
    + df["D5 Normal P"].fillna(0)
    + df["D5 Abnormal G"].fillna(0)
    + df["D5 Abnormal F"].fillna(0)
    + df["D5 Abnormal P"].fillna(0)
    + df["D6 Normal G"].fillna(0)
    + df["D6 Normal F"].fillna(0)
    + df["D6 Normal P"].fillna(0)
    + df["D6 Abnormal G"].fillna(0)
    + df["D6 Abnormal F"].fillna(0)
    + df["D6 Abnormal P"].fillna(0)
    + df["D7 Normal G"].fillna(0)
    + df["D7 Normal F"].fillna(0)
    + df["D7 Normal P"].fillna(0)
    + df["D7 Abnormal G"].fillna(0)
    + df["D7 Abnormal F"].fillna(0)
    + df["D7 Abnormal P"].fillna(0)
    + df["# 2PN"].fillna(0)
)

# calculate usable embryos per retrieved oocyte and usable embryos per mature retrieved oocyte, filling in missing values with 0
df["usable_euploid_per_retrieved"] = (
    (df["D5 Normal G"].fillna(0) 
     + df["D6 Normal G"].fillna(0) 
     + df["D7 Normal G"].fillna(0) 
     + df["D5 Normal F"].fillna(0) 
     + df["D6 Normal F"].fillna(0) 
     + df["D7 Normal F"].fillna(0))/
    df["# Egg retrieved/Thawed"].fillna(0)
)

df["usable_euploid_per_mature_retrieved"] = (
    (df["D5 Normal G"].fillna(0) 
     + df["D6 Normal G"].fillna(0) 
     + df["D7 Normal G"].fillna(0) 
     + df["D5 Normal F"].fillna(0) 
     + df["D6 Normal F"].fillna(0) 
     + df["D7 Normal F"].fillna(0))/
    df["# Mature eggs"].fillna(0)
)

# Getting totals of D5, D6, and D7 normal embryos for each cycle
df["euploid_d5"] = (
    df["D5 Normal G"].fillna(0)
    + df["D5 Normal F"].fillna(0)
    + df["D5 Normal P"].fillna(0)
)

df["euploid_d6"] = (
    df["D6 Normal G"].fillna(0)
    + df["D6 Normal F"].fillna(0)
    + df["D6 Normal P"].fillna(0)
)

df["euploid_d7"] = (
    df["D7 Normal G"].fillna(0)
    + df["D7 Normal F"].fillna(0)
    + df["D7 Normal P"].fillna(0)
)

# Filling in trigger date and retrieval date with the values from the other dataframe if they are missing in one of them

# Convert dates to datetime
df["ER Date"] = pd.to_datetime(df["ER Date"], format="%m/%d/%Y", errors="coerce")
df["retrieval_date"] = pd.to_datetime(df["retrieval_date"], errors="coerce")
df["trigger_date"] = pd.to_datetime(df["trigger_date"], errors="coerce")

# Fill missing retrieval dates from ER Date
df["retrieval_date"] = df["retrieval_date"].fillna(df["ER Date"])

# If trigger date is missing, assume 2 days before retrieval
df["trigger_date"] = df["retrieval_date"] - pd.Timedelta(days=2)

# If retrieval date is missing, assume 2 days after trigger
df["retrieval_date"] = df["trigger_date"] + pd.Timedelta(days=2)


"""
# Convert dates to datetime
df["ER Date"] = pd.to_datetime(df["ER Date"], format="%m/%d/%Y", errors="coerce")
df["retrieval_date"] = pd.to_datetime(df["retrieval_date"], errors="coerce")
df["trigger_date"] = pd.to_datetime(df["trigger_date"], errors="coerce")

# Fill missing retrieval dates from ER Date
df["retrieval_date"] = df["retrieval_date"].fillna(df["ER Date"])

# If trigger date is missing, assume 2 days before retrieval
mask = (df["status"] == "Completed") & df["trigger_date"].isna()
df.loc[mask, "trigger_date"] = df.loc[mask, "retrieval_date"] - pd.Timedelta(days=2)

# If retrieval date is missing, assume 2 days after trigger
mask = (df["status"] == "Completed") & df["retrieval_date"].isna()
df.loc[mask, "retrieval_date"] = df.loc[mask, "trigger_date"] + pd.Timedelta(days=2)
"""

'\n# Convert dates to datetime\ndf["ER Date"] = pd.to_datetime(df["ER Date"], format="%m/%d/%Y", errors="coerce")\ndf["retrieval_date"] = pd.to_datetime(df["retrieval_date"], errors="coerce")\ndf["trigger_date"] = pd.to_datetime(df["trigger_date"], errors="coerce")\n\n# Fill missing retrieval dates from ER Date\ndf["retrieval_date"] = df["retrieval_date"].fillna(df["ER Date"])\n\n# If trigger date is missing, assume 2 days before retrieval\nmask = (df["status"] == "Completed") & df["trigger_date"].isna()\ndf.loc[mask, "trigger_date"] = df.loc[mask, "retrieval_date"] - pd.Timedelta(days=2)\n\n# If retrieval date is missing, assume 2 days after trigger\nmask = (df["status"] == "Completed") & df["retrieval_date"].isna()\ndf.loc[mask, "retrieval_date"] = df.loc[mask, "trigger_date"] + pd.Timedelta(days=2)\n'

In [107]:
# count missing in retrieval_date and trigger_date
missing_retrieval_date_count = df["retrieval_date"].isna().sum()
missing_trigger_date_count = df["trigger_date"].isna().sum()

print(f"Missing retrieval_date count: {missing_retrieval_date_count}")
print(f"Missing trigger_date count: {missing_trigger_date_count}")

Missing retrieval_date count: 0
Missing trigger_date count: 0

In [108]:
display(df.head())

#merging wrong for Cesare, Catherine since accession_number is wrong (should be 25-014) in nAble

,Cycle #,Patient Name,Procedure,ER Date,Age,Donor Eggs,FDA,AMH Level,Primary Dr.,STIM D3 E2,Peak E2,Dose Increased,Menopur dosage,Follistim dosage,Clomiphene dosage,Ganirellx,Indomethacin,Lupon & Pregnyl Trigger,Endo Thickness,P4 Level,# of Follicles,# Egg retrieved/Thawed,Double Lumen,ER Dr.,ER Tech,Hyase Tech,TESA/TESE,Zymot,SW Tech,Egg FRZ,ICSI hours post ER,ICSI Tech,# Mature eggs,CC,# 2PN,# Lysed,# 0PN,# 1PN,# 3PN,# of Bx,D5 Normal G,D5 Normal F,D5 Normal P,D5 Abnormal G,D5 Abnormal F,D5 Abnormal P,D6 Normal G,D6 Normal F,D6 Normal P,D6 Abnormal G,D6 Abnormal F,D6 Abnormal P,D7 Normal G,D7 Normal F,D7 Normal P,D7 Abnormal G,D7 Abnormal F,D7 Abnormal P,# Complex ABN,# Mosaic,Chaotic,# no signal,#0PN to blast,# 0PN to Eploid blast,# 1PN to Euploid blast,# of D5 usable blast,# of D6 usable blast,# of D7 usable blast,PGT,EGG FRZ Tech,D5 Bx Tech,D5 FRZ Tech,D6 Bx Tech,D6 FRZ Tech,D7 Bx Tech,D7 FRZ Tech,Reasons for No ET,Comments,clinic,cycleid,patid_x,donorid,retrieved,retrievedby,oocytes_retrieved,complication,note,denuding_performed,denuding_performedby,retrievedtech,labassistant,scrub_tech,crna,needle_type,duration_x,accession_number,label,eventdate,response_type,retrieval_date,trigger_date,id,sart_id,patid_y,partnerid,barcode,chloe_id,height,weight,bmi,addedby,status,closed,cycletype,schedulestart,cyclestart,cycleend,scheduleend,event_labels,doctor,plan_treatment,main_note,art_reason,cycle_name,cyclecoordinator,icsi_tech,icsi_witness,insemination_tech,hist_smoker,hist_pat_surg_sterile,hist_monthsattempting,manual_culturestart,planned_start_date,planned_retrieval_date,orig_scheduleend,edd,calc_basedate,calc_type,last_prospective_report_id,last_final_report_id,pgt_reason,pgt_type,last_final_report_date,eggsource_eligibility,spermsource_eligibility,planned_eggsource,planned_spermsource,end_reason,icsi_reason,duration_y,usable_embryos,usable_euploid_per_retrieved,usable_euploid_per_mature_retrieved,euploid_d5,euploid_d6,euploid_d7
0,24-008,"Morton, Nissa",IVF Cycle,2024-01-08,41.0,N,NaN,1.61,AGA,142,4070.0,N,1350.0,2025.0,1000,NaN,NaN,NaN,8.7,6.48,21.0,28.0,N,SU,KON,KON,N,Y,KON,N,5,ZHA,13.0,N,6.0,NaN,6.0,NaN,1.0,6.0,1.0,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN,Y,NaN,ZHA,ARA,ZHA,ARA,NaN,NaN,Embryo banking,NaN,RPSD,6a6cf5b9-3e88-4beb-b826-10233c17ef58,13737,NaN,2024-01-08 08:00:00,91.0,28.0,NaN,NaN,2024-01-08 12:19:00-08,35.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,8,24-008,STIM,2023-12-28,normal,2024-01-08,2024-01-06,6a6cf5b9-3e88-4beb-b826-10233c17ef58,n_9352,13737,9028.0,36734,3678,165.10,75.750016,27.79,66,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-11-13,2023-12-28,2024-01-24,2024-01-24,NaN,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,Lab Plan: ICSI with ZyMot (if possible) - has ...,ARTReason_15=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,66.0,39.0,30.0,39.0,0.0,-1.0,12.0,NaN,2023-12-28,NaN,2024-03-27,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Aneuploidy Screening for Advanced Age,NaN,2024-10-31 13:28:36.863117-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,33001499,NaN,Laboratory routine,27.0,18.0,0.035714,0.076923,1.0,0.0,0.0
1,24-013,"Limon, Noerena",IVF Cycle,2024-01-09,41.0,N,NaN,4.24,AGA,69,5942.0,N,825.0,1025.0,800,NaN,NaN,NaN,10.2,10.78,11.0,37.0,N,DUL,KON,ARA,N,Y,CRU,N,5,ZHA,27.0,N,18.0,7.0,2.0,NaN,NaN,4.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,Y,NaN,ZHA,ARA,KIM,ARA,NaN,NaN,No normal blast,NaN,RPSD,a18856fe-981b-4d75-8b64-c737c3e5b929,29872,NaN,2024-01-09 09:15:00,90.0,37.0,NaN,NaN,2024-01-09 13:30:00-08,32.0,35.0,309.0,1366.0,Leann Johnson,Cook Echotip 16 G,10,24-013,STIM,2023-12-27,normal,2024-01-09,2024-01-07,a18856fe-981b-4d75-8b64-c737c3e5b929,n_9344,29872,29873.0,36732,3425,165.10,67.272364,24.68,44,Completed,True,ac36dd51-7809-4975-83de-48cda51987f5,2023-11-26,2023-12-27,2024-01-15,2024-01-15,NaN,6,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI with ZyMot, CC, AH, PGT-A, and ...",ARTReason_8=on,IVF: Freeze All - Autologous: BCPA Gonadotropi...,44.0,39.0,287.0,39.0,0.0,-1.0,0.0,NaN,2023-11-26,NaN,2024-01-13,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Aneuploidy Screening for Advanced Age,PGT-A,2024-10-31 13:28:36.765991-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,6517,6518,NaN,Laboratory routine,19.0,26.0,0.000000,0.000000,0.0,0.0,0.0
2,24-014,"Cesare, Catherine",IVF Cycle,2024-01-09,32.0,N,NaN,1.88,GAR,71,1445.0,Y,2400.0,2400.0,1100,Y,NaN,NaN,7.4,NaN,6.0,20.0,N,GAR,KON,KIM,N,Y,CRU,N,4,ZHA,14.0,N,11.0,1.0,2.0,NaN,NaN,10.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,1.0,Y,NaN,ZHA,ARA,KIM,ARA,KIM,TIN,Embryo banking,NaN,RPSD,78829591-54f9-4684-ab6f-ed68d4936801,41488,NaN,2024-01-09 11:01:00,3.0,20.0,NaN,Dishes verified by a 2nd Embryologist: Reviewe...,2024-01-09 14:33:00-08,287.0,35.0,309.0,285.0,Leann Johnson,Cook Echotip 16 G,11,24-014,STIM,2023-12-28,normal,2024-01-09,2024-01-07,78829591-54f9-4684-ab6f-ed68d4936801,n_9348,41488,41489.0,36774,3605,172.72,86.545527,29.01,66,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-11-11,2023-12-28,2024-01-23,2024-01-23,NaN,1,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI with ZyMot, CC, AH, PGT-A/M, an...",ARTReason_13=on&ARTReason_13_PGT=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,66.0,39.0,287.0,39.0,0.0,-1.0,13.0,NaN,2023-12-28,NaN,2024-03-25,NaN,NaN,NaN,8f6e8e65-dfe2-4bca-8d45-1d3119745ebf,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Either genetic parent is a known carrier of a ...,NaN,2024-10-31 13:28:36.811054-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,18133,18134,NaN,"Abnormal semen parameters, Laboratory routine",26.0,31.0,0.300000,0.428571,3.0,2.0,1.0
3,24-014,"Cesare, Catherine",IVF Cycle,2024-01-09,32.0,N,NaN,1.88,GAR,71,1445.0,Y,2400.0,2400.0,1100,Y,NaN,NaN,7.4,NaN,6.0,20.0,N,GAR,KON,KIM,N,Y,CRU,N,4,ZHA,14.0,N,11.0,1.0,2.0,NaN,NaN,10.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,1.0,Y,NaN,ZHA,ARA,KIM,ARA,KIM,TIN,Embryo banking,NaN,RPSD,c36a84c5-c236-4f89-91f2-c4fcba3dae65,72673,NaN,2025-01-08 11:22:00,3.0,7.0,NaN,NaN,2025-01-08 14:10:00-08,37.0,35.0,2487.0,1431.0,Leann Johnson,Double lumen needle,30,24-014,STIM,2024-12-26,normal,2025-01-08,2025-01-06,c36a84c5-c236-4f89-91f2-c4fcba3dae65,n_12973,72673,72674.0,87948,33991,160.02,55.519772,21.68,1497,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2024-11-09,2024-12-26,2025-01-30,2025-01-30,NaN,5,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI, CC, AH, PGT-A with Igenomix, a...",ARTReason_7=on,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1497.0,37.0,39.0,37.0,-98.0,-98.0,0.0,NaN,NaN,NaN,2025-03-24,NaN,NaN,NaN,7ab22d8d-08ce-43b3-9297-85f62e8028ea,091cafe9-ea4b-4778-aff4-f71296d3d2af,Aneuploidy Screening for Advanced Age,NaN,2025-11-12 17:35:31.454311-08,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,49318,49319,NaN,Laboratory routine,35.0,31.0,0.300000,0.428571,3.0,2.0,1.0
4,24-016,"Aspis, Victoria",IVF Cycle,2024-01-11,36.0,N,NaN,2.76,STAN,102,1790.0,N,825.0,1550.0,600,NaN,Y,Y,9.7,9.55,15.0,17.0,N,STAN,ARA,KIM,N,N,CRU,N,4.5,KIM,16.0,Y,11.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,6.0,NaN,Y,NaN,ZHA,TIN,ZHA,TIN,NaN,NaN,Embryo banking,NaN,RPSD,8da1aec1-69f6-4241-9a16-e665499f50be,46141,NaN,2024-01-11 07:40:00,89.0,17.0,NaN,NaN,2024-01-11 11:40:00-08,287.0,32.0,31.0,1366.0,Leann Johnson,Cook Echotip 16 G,12,24-016,STIM,2023-12-29,normal,2024-01-11,2024-01-09,8da1aec1-69f6-4241-9a16-e665499f50be,n_9375,46141,46142.0,37326,3474,149.86,51.255999,22.82,1563,Completed,True,5cf37237-dd8c-4bcc-ae5e-3da7717a21cb,2023-11-14,2023-12-29,2024-01-24,2024-01-24,NaN,43,4e625189-d13b-4ca1-9f4d-463506ae7a5f,"Lab Plan: ICSI, CC, AH, PGT-A with Igenomix, a...",NaN,IVF: Freeze All - Autologous: MLEA Gonadotropi...,1563.0,287.0,31.0,287.0,-98.0,-98.0,1.0,NaN,2023-11-14,2024-01-10,2024-03-28,NaN,NaN,NaN,NaN,ffaa69eb-92ce-4b55-89e4-36efae0f94c4,Aneuploidy Screening for Recurrent Miscarriage,PGT-A,2024-10-31 13:28:36.900047-07,Autologous/SIP Use Only Not Evaluated for Infe...,Autologous/SIP Use Only Not Evaluated for Infe...,NaN,NaN,NaN,Laboratory routine,26.0,25.0,0.117647,0.125000,0.0,3.0,0.0